// v2_el/src/views/dormitoryAllocation/DormitoryAllocationList.vue
<template>
  <div class="dormitory-allocation-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>宿舍分配信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="searchParams">
      <el-form-item label="房间号" prop="roomNumber">
        <el-input v-model="searchParams.roomNumber" placeholder="请选择房间号" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryRoom"></i>
        </el-input>
      </el-form-item>
      <el-form-item label="学生姓名" prop="studentName">
        <el-input v-model="searchParams.studentName" placeholder="请选择学生姓名" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findStudent"></i>
        </el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="pageData.list"
      border
      v-loading="pageData.loading"
      size="mini"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="roomNumber" label="房间号"></el-table-column>
      <el-table-column prop="studentName" label="学生姓名"></el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="paginationChange"
        :current-page="pageData.current"
        :page-sizes="pageData.pageSizes"
        :page-size="pageData.size"
        background
        layout="total, prev, pager, next, jumper"
        :total="pageData.count">
      </el-pagination>
    </div>
    <el-dialog :visible.sync="dormitoryRoomSelectorVisible" v-if="dormitoryRoomSelectorVisible" title="宿舍房间信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <dormitory-room-selector @dormitory-room-selected-event="handleDormitoryRoomSelectedEvent">
      </dormitory-room-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentSelectorVisible" v-if="studentSelectorVisible" title="学生信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <student-selector @student-selected-event="handleStudentSelectedEvent">
      </student-selector>
    </el-dialog>
    <el-dialog :visible.sync="dormitoryAllocationAddVisible" v-if="dormitoryAllocationAddVisible" :title="dormitoryAllocationAddTitle" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <dormitory-allocation-add :id="selectedDormitoryAllocationId" @close-dormitory-allocation-add-event="handleCloseDormitoryAllocationAddEvent" @reset-dormitory-allocation-add-event="handleResetDormitoryAllocationAddEvent">
      </dormitory-allocation-add>
    </el-dialog>
    <el-dialog :visible.sync="dormitoryAllocationViewVisible" v-if="dormitoryAllocationViewVisible" title="宿舍分配信息详情" :top="dialogTop" :width="dialogWidth">
      <dormitory-allocation-view :id="selectedDormitoryAllocationId" @close-dormitory-allocation-view-event="handleCloseDormitoryAllocationViewEvent">
      </dormitory-allocation-view>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryAllocationApi from '@/api/dormitoryAllocationApi'
import DormitoryRoomSelector from "@/views/dormitoryRoom/DormitoryRoomSelector.vue";
import StudentSelector from "@/views/student/StudentSelector.vue";
import DormitoryAllocationAdd from "@/views/dormitoryAllocation/DormitoryAllocationAdd.vue"
import DormitoryAllocationView from "@/views/dormitoryAllocation/DormitoryAllocationView.vue"
import listQueryMixin from '@/mixins/listQueryMixin'

export default {
  name: 'DormitoryAllocationList',
  components: {DormitoryRoomSelector,StudentSelector,DormitoryAllocationAdd, DormitoryAllocationView},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
      },
      dormitoryRoomSelectorVisible: false,
      studentSelectorVisible: false,
      dormitoryAllocationAddVisible: false,
      dormitoryAllocationAddTitle: '',
      dormitoryAllocationViewVisible: false,
      selectedDormitoryAllocationId: 0
    }
  },
  methods: {
    getPageData (p) {
      return dormitoryAllocationApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    onAdd () {
      this.selectedDormitoryAllocationId = ''
      this.dormitoryAllocationAddVisible = true
      this.dormitoryAllocationAddTitle = '宿舍分配信息新增'
    },
    onExport () {
      const headers = ['房间号', '学生姓名']
      const params = Object.assign(this.getPaginationParams(), this.searchParams)
      this.getPageData(params).then(data => {
        if (!data || !data.data || data.data.list.length < 1) {
          this.$message.error('无数据导出')
          return
        }
        const exportData = []
        for (const d of data.data.list) {
          exportData.push([d.roomNumber, d.studentName])
        }
        this.exportToExcel(headers, exportData)
      })
    },
    editRow (id) {
      this.selectedDormitoryAllocationId = id
      this.dormitoryAllocationAddVisible = true
      this.dormitoryAllocationAddTitle = '宿舍分配信息编辑'
    },
    delRow (id) {
      if (!id) {
        return
      }
      this.$confirm('确定要删除吗?', '删除提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        dormitoryAllocationApi.del(id)
          .then((resp) => {
            if (resp && resp.code === 1) {
              this.$message.success('删除成功!')
              this.onSearch()
            } else {
              this.$message.error('删除失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          })
          .catch(error => {
            console.error('操作失败:', error)
          })
      }).catch(() => {})
    },
    detailRow (id) {
      this.selectedDormitoryAllocationId = id
      this.dormitoryAllocationViewVisible = true
    },
    findDormitoryRoom () {
      this.dormitoryRoomSelectorVisible = true
    },
    handleDormitoryRoomSelectedEvent (selectedDormitoryRoom) {
      this.dormitoryRoomSelectorVisible = false
      if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom && this.searchParams.roomId !== selectedDormitoryRoom['roomId']) {
        this.searchParams.roomId = selectedDormitoryRoom['roomId']
        this.searchParams.roomNumber = selectedDormitoryRoom['roomNumber']
      }
    },
    findStudent () {
      this.studentSelectorVisible = true
    },
    handleStudentSelectedEvent (selectedStudent) {
      this.studentSelectorVisible = false
      if (selectedStudent && 'studentId' in selectedStudent && this.searchParams.studentId !== selectedStudent['studentId']) {
        this.searchParams.studentId = selectedStudent['studentId']
        this.searchParams.studentName = selectedStudent['studentName']
      }
    },
    handleCloseDormitoryAllocationViewEvent () {
      this.dormitoryAllocationViewVisible = false
    },
    handleResetDormitoryAllocationAddEvent () {
      this.dormitoryAllocationAddTitle = '宿舍分配信息新增'
    },
    handleCloseDormitoryAllocationAddEvent (params) {
      if (params && params.search) {
        this.onSearch()
      }
      this.dormitoryAllocationAddVisible = false
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/dormitoryAllocation/DormitoryAllocationList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {DormitoryAllocation} from "@/types/resp/dormitoryAllocation";
import dormitoryAllocationApi from '@/api/dormitoryAllocationApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import DormitoryAllocationAdd from "@/pages/dormitoryAllocation/DormitoryAllocationAdd.tsx";
import DormitoryAllocationView from "@/pages/dormitoryAllocation/DormitoryAllocationView.tsx";
import DormitoryRoomSelector from "@/pages/dormitoryRoom/DormitoryRoomSelector.tsx";
import StudentSelector from "@/pages/student/StudentSelector.tsx";
import dormitoryFeeApi from "@/api/dormitoryFeeApi.ts";
import {exportToExcel} from "@/utils/exportUtil.ts";


const DormitoryAllocationList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '宿舍分配信息列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<DormitoryAllocation[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<DormitoryAllocation>> = await dormitoryAllocationApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<DormitoryAllocation> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<DormitoryAllocation>['columns'] = [
    {title: '房间号', dataIndex: 'roomNumber', key: 'roomNumber'},
    {title: '学生姓名', dataIndex: 'studentName', key: 'studentName'},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [dormitoryAllocationAddVisible, setDormitoryAllocationAddVisible] = useState(false);
  const [dormitoryAllocationViewVisible, setDormitoryAllocationViewVisible] = useState(false);
  const [selectedDormitoryAllocationId, setSelectedDormitoryAllocationId] = useState(0)
  const [selectedDormitoryAllocation, setSelectedDormitoryAllocation] = useState({})

  const onAdd = () => {
    setSelectedDormitoryAllocationId(0)
    setDormitoryAllocationAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedDormitoryAllocationId(id)
    setDormitoryAllocationAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      dormitoryAllocationApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: DormitoryAllocation) => {
    setSelectedDormitoryAllocation(record)
    setDormitoryAllocationViewVisible(true)
  };

  const [dormitoryRoomSelectorVisible, setDormitoryRoomSelectorVisible] = useState(false);
  const findDormitoryRoom = () => {
    setDormitoryRoomSelectorVisible(true);
  }
  const handleDormitoryRoomSelected = (selectedDormitoryRoom: { roomId?: number; roomNumber?: string; }) => {
    setDormitoryRoomSelectorVisible(false)
    if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      roomId: selectedDormitoryRoom['roomId'],
      roomNumber: selectedDormitoryRoom['roomNumber'],
      }));
    }
  };
  const handleCloseDormitoryRoomSelector = () => {
    setDormitoryRoomSelectorVisible(false)
  };
  const [studentSelectorVisible, setStudentSelectorVisible] = useState(false);
  const findStudent = () => {
    setStudentSelectorVisible(true);
  }
  const handleStudentSelected = (selectedStudent: { studentId?: number; studentName?: string; }) => {
    setStudentSelectorVisible(false)
    if (selectedStudent && 'studentId' in selectedStudent) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      studentId: selectedStudent['studentId'],
      studentName: selectedStudent['studentName'],
      }));
    }
  };
  const handleCloseStudentSelector = () => {
    setStudentSelectorVisible(false)
  };

  const handleCloseDormitoryAllocationAdd = () => {
    setDormitoryAllocationAddVisible(false)
  };

  const handleCloseDormitoryAllocationView = () => {
    setDormitoryAllocationViewVisible(false)
  };

  const onExport = () => {
    const headers = ['房间号', '学生姓名']
    dormitoryFeeApi.find(form.getFieldsValue()).then(data => {
      if (!data || !data.data || data.data.list.length < 1) {
        messageApi.error('无数据导出')
        return
      }
      const exportData = []
      for (const d of data.data.list) {
        exportData.push([d.roomNumber, d.studentName])
      }
      exportToExcel(headers, exportData)
    })
  }

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="dormitoryAllocationList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="roomNumber" label="房间号">
          <Input.Search placeholder="请选择房间号" onSearch={findDormitoryRoom} readOnly={true} />
        </Form.Item>
        <Form.Item name="studentName" label="学生姓名">
          <Input.Search placeholder="请选择学生姓名" onSearch={findStudent} readOnly={true} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onExport}>导出</Button>
        </Form.Item>
      </Form>
      <Table<DormitoryAllocation> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <DormitoryRoomSelector visible={dormitoryRoomSelectorVisible} onDormitoryRoomSelected={handleDormitoryRoomSelected} onCloseDormitoryRoomSelector={handleCloseDormitoryRoomSelector} />
      <StudentSelector visible={studentSelectorVisible} onStudentSelected={handleStudentSelected} onCloseStudentSelector={handleCloseStudentSelector} />
      <DormitoryAllocationAdd visible={dormitoryAllocationAddVisible} onCloseDormitoryAllocationAdd={handleCloseDormitoryAllocationAdd} id={selectedDormitoryAllocationId} />
      <DormitoryAllocationView visible={dormitoryAllocationViewVisible} onCloseDormitoryAllocationView={handleCloseDormitoryAllocationView} viewRow={selectedDormitoryAllocation} />
    </div>
  );
};

export default DormitoryAllocationList;
