// v2_el/src/views/dormitoryAllocation/DormitoryAllocationAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryAllocationForm" :label-width="formLabelWidth" ref="refDormitoryAllocationForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房间号" prop="roomNumber">
            <el-input v-model="dormitoryAllocationForm.roomNumber" placeholder="请选择房间号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="学生姓名" prop="studentName">
            <el-input v-model="dormitoryAllocationForm.studentName" placeholder="请选择学生姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStudent"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="dormitoryRoomSelectorVisible" v-if="dormitoryRoomSelectorVisible" title="宿舍房间信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <dormitory-room-selector @dormitory-room-selected-event="handleDormitoryRoomSelectedEvent">
      </dormitory-room-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentSelectorVisible" v-if="studentSelectorVisible" title="学生信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <student-selector @student-selected-event="handleStudentSelectedEvent">
      </student-selector>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryAllocationApi from '@/api/dormitoryAllocationApi'
import DormitoryRoomSelector from "@/views/dormitoryRoom/DormitoryRoomSelector.vue";
import StudentSelector from "@/views/student/StudentSelector.vue";
export default {
  name: 'DormitoryAllocationAdd',
  components: {DormitoryRoomSelector,StudentSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryAllocationForm: {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
      },
      rules: {
        roomNumber: [
          { required: true, message: '请输入房间号', trigger: 'blur' }
        ],
        studentName: [
          { required: true, message: '请输入学生姓名', trigger: 'blur' }
        ],
      },
      dormitoryRoomSelectorVisible: false,
      studentSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      dormitoryAllocationApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.dormitoryAllocationForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.dormitoryAllocationForm = {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
      }
      this.$emit('reset-dormitory-allocation-add-event')
    },
    onSave () {
      this.$refs.refDormitoryAllocationForm.validate((valid) => {
        if (valid) {
          dormitoryAllocationApi.save(this.dormitoryAllocationForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-dormitory-allocation-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findDormitoryRoom () {
      this.dormitoryRoomSelectorVisible = true
    },
    handleDormitoryRoomSelectedEvent (selectedDormitoryRoom) {
      this.dormitoryRoomSelectorVisible = false
      if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom && this.dormitoryAllocationForm.roomId !== selectedDormitoryRoom['roomId']) {
        this.dormitoryAllocationForm.roomId = selectedDormitoryRoom['roomId']
        this.dormitoryAllocationForm.roomNumber = selectedDormitoryRoom['roomNumber']
      }
    },
    findStudent () {
      this.studentSelectorVisible = true
    },
    handleStudentSelectedEvent (selectedStudent) {
      this.studentSelectorVisible = false
      if (selectedStudent && 'studentId' in selectedStudent && this.dormitoryAllocationForm.studentId !== selectedStudent['studentId']) {
        this.dormitoryAllocationForm.studentId = selectedStudent['studentId']
        this.dormitoryAllocationForm.studentName = selectedStudent['studentName']
      }
    },
    onBack () {
      this.$emit('close-dormitory-allocation-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/dormitoryAllocation/DormitoryAllocationAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import dormitoryAllocationApi from "@/api/dormitoryAllocationApi.ts";
import {DormitoryAllocation} from "@/types/resp/dormitoryAllocation";
import DormitoryRoomSelector from "@/pages/dormitoryRoom/DormitoryRoomSelector.tsx";
import StudentSelector from "@/pages/student/StudentSelector.tsx";

interface DormitoryAllocationAddProps {
  visible: boolean;
  id: number;
  onCloseDormitoryAllocationAdd: () => void;
}

const DormitoryAllocationAdd: React.FC<DormitoryAllocationAddProps> = ({visible, id, onCloseDormitoryAllocationAdd}) => {

  const [form] = Form.useForm<DormitoryAllocation>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    roomNumber: [
      { required: true, message: '请输入房间号' }
    ],
    studentName: [
      { required: true, message: '请输入学生姓名' }
    ],
  };

  let dormitoryAllocationForm: Partial<DormitoryAllocation> = {}

  const [title, setTitle] = useState('新增宿舍分配信息');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑宿舍分配信息')
      initDormitoryAllocationFormById(id)
    } else {
      setTitle('新增宿舍分配信息')
      form.resetFields();
    }
  }, [visible]);

  const initDormitoryAllocationFormById = async (id: number) => {
    const resp: Result<DormitoryAllocation> = await dormitoryAllocationApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      dormitoryAllocationForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let dormitoryAllocation2Save:DormitoryAllocation = form.getFieldsValue()
      if (id) {
        dormitoryAllocation2Save = Object.assign(dormitoryAllocationForm, dormitoryAllocation2Save)
      }
      const resp: Result<void> = await dormitoryAllocationApi.save(dormitoryAllocation2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增宿舍分配信息')
    form.resetFields();
  };
  
  const [dormitoryRoomSelectorVisible, setDormitoryRoomSelectorVisible] = useState(false);
  const findDormitoryRoom = () => {
    setDormitoryRoomSelectorVisible(true);
  }
  const handleDormitoryRoomSelected = (selectedDormitoryRoom: { roomId?: number; roomNumber?: string; }) => {
    setDormitoryRoomSelectorVisible(false)
    if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      roomId: selectedDormitoryRoom['roomId'],
      roomNumber: selectedDormitoryRoom['roomNumber'],
      }));
    }
  };
  const handleCloseDormitoryRoomSelector = () => {
    setDormitoryRoomSelectorVisible(false)
  };
  const [studentSelectorVisible, setStudentSelectorVisible] = useState(false);
  const findStudent = () => {
    setStudentSelectorVisible(true);
  }
  const handleStudentSelected = (selectedStudent: { studentId?: number; studentName?: string; }) => {
    setStudentSelectorVisible(false)
    if (selectedStudent && 'studentId' in selectedStudent) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      studentId: selectedStudent['studentId'],
      studentName: selectedStudent['studentName'],
      }));
    }
  };
  const handleCloseStudentSelector = () => {
    setStudentSelectorVisible(false)
  };

  const onBack = () => {
    onCloseDormitoryAllocationAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseDormitoryAllocationAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="dormitoryAllocationForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号" rules={rules.roomNumber}>
              <Input.Search placeholder="请选择房间号" onSearch={findDormitoryRoom} readOnly={true} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="studentName" label="学生姓名" rules={rules.studentName}>
              <Input.Search placeholder="请选择学生姓名" onSearch={findStudent} readOnly={true} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
      <DormitoryRoomSelector visible={dormitoryRoomSelectorVisible} onDormitoryRoomSelected={handleDormitoryRoomSelected} onCloseDormitoryRoomSelector={handleCloseDormitoryRoomSelector} />
      <StudentSelector visible={studentSelectorVisible} onStudentSelected={handleStudentSelected} onCloseStudentSelector={handleCloseStudentSelector} />
    </Modal>
  )
}

export default DormitoryAllocationAdd;
