// react_antd/src/pages/dormitoryFee/DormitoryFeeView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {DormitoryFee} from "@/types/resp/dormitoryFee";

interface DormitoryFeeViewProps {
  visible: boolean;
  viewRow: object;
  onCloseDormitoryFeeView: () => void;
}

const DormitoryFeeView: React.FC<DormitoryFeeViewProps> = ({visible, viewRow, onCloseDormitoryFeeView}) => {

  const [form] = Form.useForm<DormitoryFee>();

  const onBack = () => {
    onCloseDormitoryFeeView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"费用信息详情"} open={visible} onCancel={onCloseDormitoryFeeView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="studentName" label="学生姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="feeType" label="费用类型">
              <Select placeholder="请选择费用类型" options={[
                { value: 10, label: <span>住宿费</span> },
                { value: 20, label: <span>网费</span> },
                { value: 30, label: <span>水费</span> },
                { value: 40, label: <span>电费</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="feePeriodType" label="收费周期类型">
              <Select placeholder="请选择收费周期类型" options={[
                { value: 10, label: <span>月度</span> },
                { value: 20, label: <span>年度</span> },
                { value: 30, label: <span>季度</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="feePeriod" label="收费周期">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="feeAmount" label="费用金额">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default DormitoryFeeView;

// angular_ngzorro/src/app/dormitory-fee/dormitory-fee-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {DormitoryFee} from '../../types/resp/DormitoryFee';

@Component({
  selector: 'dormitory-fee-view',
  imports: [
    SharedModule
  ],
  templateUrl: './dormitory-fee-view.component.html',
  standalone: true
})
export class DormitoryFeeViewComponent implements OnInit {
  dormitoryFeeForm!: FormGroup;
  isVisible: boolean = false
  title: string = '费用信息详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.dormitoryFeeForm = this.fb.group({
      roomNumber: [''],
      studentName: [''],
      feeType: [undefined],
      feePeriodType: [undefined],
      feePeriod: [''],
      feeAmount: [0],
      createTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(dormitoryFee: DormitoryFee) {
    this.isVisible = true
    this.dormitoryFeeForm.patchValue(dormitoryFee);
    this.dormitoryFeeForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryFeeForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房间号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentName">学生姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="studentName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feeType">费用类型</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="feeType">
                <nz-option nzLabel="住宿费" [nzValue]="10"></nz-option>
                <nz-option nzLabel="网费" [nzValue]="20"></nz-option>
                <nz-option nzLabel="水费" [nzValue]="30"></nz-option>
                <nz-option nzLabel="电费" [nzValue]="40"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feePeriodType">收费周期类型</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="feePeriodType">
                <nz-option nzLabel="月度" [nzValue]="10"></nz-option>
                <nz-option nzLabel="年度" [nzValue]="20"></nz-option>
                <nz-option nzLabel="季度" [nzValue]="30"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feePeriod">收费周期</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="feePeriod" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feeAmount">费用金额</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="feeAmount" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
