// v2_el/src/views/dormitoryFee/DormitoryFeeAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryFeeForm" :label-width="formLabelWidth" ref="refDormitoryFeeForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房间号" prop="roomNumber">
            <el-input v-model="dormitoryFeeForm.roomNumber" placeholder="请选择房间号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="学生姓名" prop="studentName">
            <el-input v-model="dormitoryFeeForm.studentName" placeholder="请选择学生姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStudent"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="费用类型" prop="feeType">
            <el-select v-model="dormitoryFeeForm.feeType" placeholder="请选择费用类型">
              <el-option label="住宿费" :value="10"></el-option>
              <el-option label="网费" :value="20"></el-option>
              <el-option label="水费" :value="30"></el-option>
              <el-option label="电费" :value="40"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="收费周期类型" prop="feePeriodType">
            <el-select v-model="dormitoryFeeForm.feePeriodType" placeholder="请选择收费周期类型">
              <el-option label="月度" :value="10"></el-option>
              <el-option label="年度" :value="20"></el-option>
              <el-option label="季度" :value="30"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="收费周期" prop="feePeriod">
            <el-input v-model="dormitoryFeeForm.feePeriod" placeholder="请输入收费周期" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="费用金额" prop="feeAmount">
            <el-input-number v-model="dormitoryFeeForm.feeAmount" :precision="2" :step="0.1" :min="1" :max="99999999"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="dormitoryRoomSelectorVisible" v-if="dormitoryRoomSelectorVisible" title="宿舍房间信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <dormitory-room-selector @dormitory-room-selected-event="handleDormitoryRoomSelectedEvent">
      </dormitory-room-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentSelectorVisible" v-if="studentSelectorVisible" title="学生信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <student-selector @student-selected-event="handleStudentSelectedEvent">
      </student-selector>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryFeeApi from '@/api/dormitoryFeeApi'
import DormitoryRoomSelector from "@/views/dormitoryRoom/DormitoryRoomSelector.vue";
import StudentSelector from "@/views/student/StudentSelector.vue";
export default {
  name: 'DormitoryFeeAdd',
  components: {DormitoryRoomSelector,StudentSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryFeeForm: {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
        feeType: '',
        feePeriodType: '',
        feePeriod: '',
        feeAmount: ''
      },
      rules: {
        roomNumber: [
          { required: true, message: '请输入房间号', trigger: 'blur' }
        ],
        feeType: [
          { required: true, message: '请输入费用类型', trigger: 'blur' }
        ],
        feePeriodType: [
          { required: true, message: '请输入收费周期类型', trigger: 'blur' }
        ],
        feePeriod: [
          { required: true, message: '请输入收费周期', trigger: 'blur' }
        ],
        feeAmount: [
          { required: true, message: '请输入费用金额', trigger: 'blur' }
        ],
      },
      dormitoryRoomSelectorVisible: false,
      studentSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      dormitoryFeeApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.dormitoryFeeForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.dormitoryFeeForm = {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
        feeType: '',
        feePeriodType: '',
        feePeriod: '',
        feeAmount: ''
      }
      this.$emit('reset-dormitory-fee-add-event')
    },
    onSave () {
      this.$refs.refDormitoryFeeForm.validate((valid) => {
        if (valid) {
          dormitoryFeeApi.save(this.dormitoryFeeForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-dormitory-fee-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findDormitoryRoom () {
      this.dormitoryRoomSelectorVisible = true
    },
    handleDormitoryRoomSelectedEvent (selectedDormitoryRoom) {
      this.dormitoryRoomSelectorVisible = false
      if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom && this.dormitoryFeeForm.roomId !== selectedDormitoryRoom['roomId']) {
        this.dormitoryFeeForm.roomId = selectedDormitoryRoom['roomId']
        this.dormitoryFeeForm.roomNumber = selectedDormitoryRoom['roomNumber']
      }
    },
    findStudent () {
      this.studentSelectorVisible = true
    },
    handleStudentSelectedEvent (selectedStudent) {
      this.studentSelectorVisible = false
      if (selectedStudent && 'studentId' in selectedStudent && this.dormitoryFeeForm.studentId !== selectedStudent['studentId']) {
        this.dormitoryFeeForm.studentId = selectedStudent['studentId']
        this.dormitoryFeeForm.studentName = selectedStudent['studentName']
      }
    },
    onBack () {
      this.$emit('close-dormitory-fee-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/dormitory-fee/dormitory-fee-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {DormitoryFeeService} from '../../service/dormitory-fee.service';
import {SharedModule} from '../shared.module';
import {DormitoryFeeForm} from '../../types/req/DormitoryFeeForm';
import {MODAL_WIDTH} from '../../const'
import {DormitoryRoomSelectorComponent} from '../dormitory-room/dormitory-room-selector.component';
import {StudentSelectorComponent} from '../student/student-selector.component';

@Component({
  selector: 'dormitory-fee-add',
  imports: [
    DormitoryRoomSelectorComponent,
    StudentSelectorComponent,
    SharedModule
  ],
  templateUrl: './dormitory-fee-add.component.html',
  standalone: true
})
export class DormitoryFeeAddComponent implements OnInit {
  dormitoryFeeToSave:DormitoryFeeForm = {};
  dormitoryFeeForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增费用信息'
  modalWidth: string = MODAL_WIDTH
  

  @ViewChild(DormitoryRoomSelectorComponent, { static: false }) dormitoryRoomSelectorComponent!: DormitoryRoomSelectorComponent;
  @ViewChild(StudentSelectorComponent, { static: false }) studentSelectorComponent!: StudentSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private dormitoryFeeService: DormitoryFeeService
  ) {}

  ngOnInit(): void {
    this.dormitoryFeeForm = this.fb.group({
      roomId: [0],
      roomNumber: ['', [Validators.required]],
      studentId: [0],
      studentName: [''],
      feeType: [undefined, [Validators.required]],
      feePeriodType: [undefined, [Validators.required]],
      feePeriod: ['', [Validators.required]],
      feeAmount: [0, [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.dormitoryFeeForm.controls) {
        this.dormitoryFeeForm.controls[i].markAsDirty();
        this.dormitoryFeeForm.controls[i].updateValueAndValidity();
      }
      if (!this.dormitoryFeeForm.valid) {
        this.saveLoading = false
        return
      }
      this.dormitoryFeeService.save(Object.assign(this.dormitoryFeeToSave, this.dormitoryFeeForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增费用信息'.slice()
    this.dormitoryFeeForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改费用信息'
      this.saveLoading = true
      this.dormitoryFeeService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.dormitoryFeeToSave = resp.data
            this.dormitoryFeeForm.patchValue(this.dormitoryFeeToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findDormitoryRoom() {
    this.dormitoryRoomSelectorComponent.display()
  }

  handleDormitoryRoomSelectedEvent(selectedDormitoryRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom) {
      this.dormitoryFeeForm.patchValue(selectedDormitoryRoom);
    }
  }
  findStudent() {
    this.studentSelectorComponent.display()
  }

  handleStudentSelectedEvent(selectedStudent: { studentId?: number; studentName?: string; }) {
    if (selectedStudent && 'studentId' in selectedStudent) {
      this.dormitoryFeeForm.patchValue(selectedStudent);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryFeeForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房间号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房间号'">
              <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
                <input nz-input formControlName="roomNumber" placeholder="请选择房间号" readonly />
              </nz-input-group>
              <ng-template #roomNumberSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findDormitoryRoom()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentName">学生姓名</nz-form-label>
            <nz-form-control>
              <nz-input-group nzSearch [nzAddOnAfter]="studentNameSuffixIconButton">
                <input nz-input formControlName="studentName" placeholder="请选择学生姓名" readonly />
              </nz-input-group>
              <ng-template #studentNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findStudent()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feeType" nzRequired>费用类型</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择费用类型'">
              <nz-select formControlName="feeType">
                <nz-option nzLabel="住宿费" [nzValue]="10"></nz-option>
                <nz-option nzLabel="网费" [nzValue]="20"></nz-option>
                <nz-option nzLabel="水费" [nzValue]="30"></nz-option>
                <nz-option nzLabel="电费" [nzValue]="40"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feePeriodType" nzRequired>收费周期类型</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择收费周期类型'">
              <nz-select formControlName="feePeriodType">
                <nz-option nzLabel="月度" [nzValue]="10"></nz-option>
                <nz-option nzLabel="年度" [nzValue]="20"></nz-option>
                <nz-option nzLabel="季度" [nzValue]="30"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feePeriod" nzRequired>收费周期</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入收费周期'">
              <input nz-input formControlName="feePeriod" placeholder="请输入收费周期" maxlength="32"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="feeAmount" nzRequired>费用金额</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择费用金额'">
            <nz-input-number formControlName="feeAmount" [nzMin]="1" [nzMax]="99999999" [nzPrecision]="2" [nzStep]="0.1" nzPlaceHolder="Digital" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<dormitory-room-selector (dormitoryRoomSelectedEvent)="handleDormitoryRoomSelectedEvent($event)"></dormitory-room-selector>
<student-selector (studentSelectedEvent)="handleStudentSelectedEvent($event)"></student-selector>
