// angular_ngzorro/src/app/admin/admin-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {AdminService} from '../../service/admin.service';
import {SharedModule} from '../shared.module';
import {AdminForm} from '../../types/req/AdminForm';
import {MODAL_WIDTH} from '../../const'

@Component({
  selector: 'admin-add',
  imports: [
    SharedModule
  ],
  templateUrl: './admin-add.component.html',
  standalone: true
})
export class AdminAddComponent implements OnInit {
  adminToSave:AdminForm = {};
  adminForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增管理员'
  modalWidth: string = MODAL_WIDTH

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private adminService: AdminService
  ) {}

  ngOnInit(): void {
    this.adminForm = this.fb.group({
    username: ['', [Validators.required]],
    password: ['', [Validators.required]],
    name: ['', [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.adminForm.controls) {
        this.adminForm.controls[i].markAsDirty();
        this.adminForm.controls[i].updateValueAndValidity();
      }
      if (!this.adminForm.valid) {
        this.saveLoading = false
        return
      }
      this.adminService.save(Object.assign(this.adminToSave, this.adminForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增管理员'.slice()
    this.adminForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改管理员'
      this.saveLoading = true
      this.adminService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.adminToSave = resp.data
            this.adminForm.patchValue(this.adminToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="adminForm" (ngSubmit)="onSave()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="username" nzRequired>用户名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入用户名'">
              <input nz-input formControlName="username" placeholder="请输入用户名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入密码'">
              <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// v3_el/src/views/admin/AdminAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form label-position="right" :model="adminForm" :label-width="formLabelWidth" ref="adminFormRef" :rules="rules">
        <el-row>
          <el-col :span="11">
            <el-form-item label="用户名" prop="username">
              <el-input v-model="adminForm.username" placeholder="请输入用户名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="密码" prop="password">
              <el-input v-model="adminForm.password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="adminForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import {defineEmits, defineProps, onMounted, reactive, ref, inject, toRefs} from 'vue';
import adminApi from '@/api/adminApi'
import type {FormInstance} from 'element-plus';
import {ElMessage} from 'element-plus'
import type {AdminForm} from "@/types/req/adminForm";
import type {Result} from '@/types/result'
import type {Admin} from "@/types/resp/admin";
import type {Id} from "@/types/id";

const props = defineProps<Id>()
const adminFormRef = ref<FormInstance | null>(null);
let adminForm = reactive<AdminForm>({
  username: '',
  password: '',
  name: '',
})
const emit = defineEmits<{
  (e: 'resetAdminAddEvent'): void;
  (e: 'closeAdminAddEvent', data?: { search: boolean }): void;
}>()

const rules = reactive({
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' }
  ],
  name: [
    { required: true, message: '请输入姓名', trigger: 'blur' }
  ],
});
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')
const formLabelWidth = ref<string>('')

onMounted(() => {
  if (props.id) {
    initAdminFormById(props.id)
  }
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string, formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
});

const initAdminFormById = async (id: number) => {
  const resp: Result<Admin> = await adminApi.findById(id)
  if (resp && resp.code === 1 && resp.data) {
    Object.assign(adminForm, resp.data)
  }
}

const onReset = () => {
  if (adminFormRef.value) {
    adminFormRef.value.resetFields()
  }
  emit('resetAdminAddEvent')
}

const onSave = () => {
  if (!adminFormRef.value) {
    return
  }
  adminFormRef.value.validate(async (valid: boolean) => {
    if (valid) {
      const resp: Result<void> = await adminApi.save(adminForm)
      if (resp && resp.code === 1) {
        ElMessage.success('保存成功')
        emit('closeAdminAddEvent', {search: true})
      } else {
        ElMessage.error('保存失败:' + (resp.msg ? resp.msg : ''))
      }
    }
  })
}


const onBack = () => {
  emit('closeAdminAddEvent')
}
</script>

<style lang="scss">
</style>
