// v2_el/src/views/dormitoryRoom/DormitoryRoomView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryRoomForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼栋名称">
            <el-input v-model="dormitoryRoomForm.buildingName"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房间号">
            <el-input v-model="dormitoryRoomForm.roomNumber"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="所在楼层">
            <el-input v-model="dormitoryRoomForm.floorNumber"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房间类型">
            <el-select v-model="dormitoryRoomForm.roomType" placeholder="请选择房间类型">
              <el-option label="双人间" :value="2"></el-option>
              <el-option label="四人间" :value="4"></el-option>
              <el-option label="六人间" :value="6"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="可用床位">
            <el-input v-model="dormitoryRoomForm.availableBeds"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有独立卫生间">
            <el-select v-model="dormitoryRoomForm.hasBathroom" placeholder="请选择是否有独立卫生间">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有空调">
            <el-select v-model="dormitoryRoomForm.hasAirConditioning" placeholder="请选择是否有空调">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有无线网络">
            <el-select v-model="dormitoryRoomForm.hasWifi" placeholder="请选择是否有无线网络">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="dormitoryRoomForm.createTime"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="最后修改时间">
            <el-input v-model="dormitoryRoomForm.modifyTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import dormitoryRoomApi from '@/api/dormitoryRoomApi'
export default {
  name: 'DormitoryRoomView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryRoomForm: {
      }
    }
  },
  created () {
    if (this.id) {
      dormitoryRoomApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.dormitoryRoomForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-dormitory-room-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/dormitoryRoom/DormitoryRoomView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {DormitoryRoom} from "@/types/resp/dormitoryRoom";

interface DormitoryRoomViewProps {
  visible: boolean;
  viewRow: object;
  onCloseDormitoryRoomView: () => void;
}

const DormitoryRoomView: React.FC<DormitoryRoomViewProps> = ({visible, viewRow, onCloseDormitoryRoomView}) => {

  const [form] = Form.useForm<DormitoryRoom>();

  const onBack = () => {
    onCloseDormitoryRoomView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"宿舍房间信息详情"} open={visible} onCancel={onCloseDormitoryRoomView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="buildingName" label="楼栋名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="floorNumber" label="所在楼层">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomType" label="房间类型">
              <Select placeholder="请选择房间类型" options={[
                { value: 2, label: <span>双人间</span> },
                { value: 4, label: <span>四人间</span> },
                { value: 6, label: <span>六人间</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="availableBeds" label="可用床位">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="hasBathroom" label="是否有独立卫生间">
              <Select placeholder="请选择是否有独立卫生间" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="hasAirConditioning" label="是否有空调">
              <Select placeholder="请选择是否有空调" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="hasWifi" label="是否有无线网络">
              <Select placeholder="请选择是否有无线网络" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default DormitoryRoomView;
