// v2_el/src/views/dormitoryRoom/DormitoryRoomAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryRoomForm" :label-width="formLabelWidth" ref="refDormitoryRoomForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼栋名称" prop="buildingName">
            <el-input v-model="dormitoryRoomForm.buildingName" placeholder="请选择楼栋名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryBuilding"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房间号" prop="roomNumber">
            <el-input v-model="dormitoryRoomForm.roomNumber" placeholder="请输入房间号" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="所在楼层" prop="floorNumber">
            <el-input-number v-model="dormitoryRoomForm.floorNumber" :min="1" :max="128"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房间类型" prop="roomType">
            <el-select v-model="dormitoryRoomForm.roomType" placeholder="请选择房间类型">
              <el-option label="双人间" :value="2"></el-option>
              <el-option label="四人间" :value="4"></el-option>
              <el-option label="六人间" :value="6"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有独立卫生间" prop="hasBathroom">
            <el-select v-model="dormitoryRoomForm.hasBathroom" placeholder="请选择是否有独立卫生间">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有空调" prop="hasAirConditioning">
            <el-select v-model="dormitoryRoomForm.hasAirConditioning" placeholder="请选择是否有空调">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有无线网络" prop="hasWifi">
            <el-select v-model="dormitoryRoomForm.hasWifi" placeholder="请选择是否有无线网络">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="dormitoryBuildingSelectorVisible" v-if="dormitoryBuildingSelectorVisible" title="宿舍楼栋信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <dormitory-building-selector @dormitory-building-selected-event="handleDormitoryBuildingSelectedEvent">
      </dormitory-building-selector>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryRoomApi from '@/api/dormitoryRoomApi'
import DormitoryBuildingSelector from "@/views/dormitoryBuilding/DormitoryBuildingSelector.vue";
export default {
  name: 'DormitoryRoomAdd',
  components: {DormitoryBuildingSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryRoomForm: {
        buildingId: '',
        buildingName: '',
        roomNumber: '',
        floorNumber: '',
        roomType: '',
        hasBathroom: '',
        hasAirConditioning: '',
        hasWifi: ''
      },
      rules: {
        buildingName: [
          { required: true, message: '请输入楼栋名称', trigger: 'blur' }
        ],
        roomNumber: [
          { required: true, message: '请输入房间号', trigger: 'blur' }
        ],
        floorNumber: [
          { required: true, message: '请输入所在楼层', trigger: 'blur' }
        ],
        roomType: [
          { required: true, message: '请输入房间类型', trigger: 'blur' }
        ],
        hasBathroom: [
          { required: true, message: '请输入是否有独立卫生间', trigger: 'blur' }
        ],
        hasAirConditioning: [
          { required: true, message: '请输入是否有空调', trigger: 'blur' }
        ],
        hasWifi: [
          { required: true, message: '请输入是否有无线网络', trigger: 'blur' }
        ],
      },
      dormitoryBuildingSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      dormitoryRoomApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.dormitoryRoomForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.dormitoryRoomForm = {
        buildingId: '',
        buildingName: '',
        roomNumber: '',
        floorNumber: '',
        roomType: '',
        hasBathroom: '',
        hasAirConditioning: '',
        hasWifi: ''
      }
      this.$emit('reset-dormitory-room-add-event')
    },
    onSave () {
      this.$refs.refDormitoryRoomForm.validate((valid) => {
        if (valid) {
          dormitoryRoomApi.save(this.dormitoryRoomForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-dormitory-room-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findDormitoryBuilding () {
      this.dormitoryBuildingSelectorVisible = true
    },
    handleDormitoryBuildingSelectedEvent (selectedDormitoryBuilding) {
      this.dormitoryBuildingSelectorVisible = false
      if (selectedDormitoryBuilding && 'buildingId' in selectedDormitoryBuilding && this.dormitoryRoomForm.buildingId !== selectedDormitoryBuilding['buildingId']) {
        this.dormitoryRoomForm.buildingId = selectedDormitoryBuilding['buildingId']
        this.dormitoryRoomForm.buildingName = selectedDormitoryBuilding['buildingName']
      }
    },
    onBack () {
      this.$emit('close-dormitory-room-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/dormitoryRoom/DormitoryRoomAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, InputNumber, message, Modal, Row, Select} from "antd";
import type {Result} from "@/types/result";
import dormitoryRoomApi from "@/api/dormitoryRoomApi.ts";
import {DormitoryRoom} from "@/types/resp/dormitoryRoom";
import DormitoryBuildingSelector from "@/pages/dormitoryBuilding/DormitoryBuildingSelector.tsx";

interface DormitoryRoomAddProps {
  visible: boolean;
  id: number;
  onCloseDormitoryRoomAdd: () => void;
}

const DormitoryRoomAdd: React.FC<DormitoryRoomAddProps> = ({visible, id, onCloseDormitoryRoomAdd}) => {

  const [form] = Form.useForm<DormitoryRoom>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    buildingName: [
      { required: true, message: '请输入楼栋名称' }
    ],
    roomNumber: [
      { required: true, message: '请输入房间号' }
    ],
    floorNumber: [
      { required: true, message: '请输入所在楼层' }
    ],
    roomType: [
      { required: true, message: '请输入房间类型' }
    ],
    hasBathroom: [
      { required: true, message: '请输入是否有独立卫生间' }
    ],
    hasAirConditioning: [
      { required: true, message: '请输入是否有空调' }
    ],
    hasWifi: [
      { required: true, message: '请输入是否有无线网络' }
    ],
  };

  let dormitoryRoomForm: Partial<DormitoryRoom> = {}

  const [title, setTitle] = useState('新增宿舍房间信息');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑宿舍房间信息')
      initDormitoryRoomFormById(id)
    } else {
      setTitle('新增宿舍房间信息')
      form.resetFields();
    }
  }, [visible]);

  const initDormitoryRoomFormById = async (id: number) => {
    const resp: Result<DormitoryRoom> = await dormitoryRoomApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      dormitoryRoomForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let dormitoryRoom2Save:DormitoryRoom = form.getFieldsValue()
      if (id) {
        dormitoryRoom2Save = Object.assign(dormitoryRoomForm, dormitoryRoom2Save)
      }
      const resp: Result<void> = await dormitoryRoomApi.save(dormitoryRoom2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增宿舍房间信息')
    form.resetFields();
  };
  
  const [dormitoryBuildingSelectorVisible, setDormitoryBuildingSelectorVisible] = useState(false);
  const findDormitoryBuilding = () => {
    setDormitoryBuildingSelectorVisible(true);
  }
  const handleDormitoryBuildingSelected = (selectedDormitoryBuilding: { buildingId?: number; buildingName?: string; }) => {
    setDormitoryBuildingSelectorVisible(false)
    if (selectedDormitoryBuilding && 'buildingId' in selectedDormitoryBuilding) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      buildingId: selectedDormitoryBuilding['buildingId'],
      buildingName: selectedDormitoryBuilding['buildingName'],
      }));
    }
  };
  const handleCloseDormitoryBuildingSelector = () => {
    setDormitoryBuildingSelectorVisible(false)
  };

  const onBack = () => {
    onCloseDormitoryRoomAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseDormitoryRoomAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="dormitoryRoomForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="buildingName" label="楼栋名称" rules={rules.buildingName}>
              <Input.Search placeholder="请选择楼栋名称" onSearch={findDormitoryBuilding} readOnly={true} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号" rules={rules.roomNumber}>
              <Input maxLength={32} placeholder="请输入房间号"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="floorNumber" label="所在楼层" rules={rules.floorNumber}>
              <InputNumber min={1} max={128} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomType" label="房间类型" rules={rules.roomType}>
              <Select placeholder="请选择房间类型" options={[
                { value: 2, label: <span>双人间</span> },
                { value: 4, label: <span>四人间</span> },
                { value: 6, label: <span>六人间</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="hasBathroom" label="是否有独立卫生间" rules={rules.hasBathroom}>
              <Select placeholder="请选择是否有独立卫生间" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="hasAirConditioning" label="是否有空调" rules={rules.hasAirConditioning}>
              <Select placeholder="请选择是否有空调" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="hasWifi" label="是否有无线网络" rules={rules.hasWifi}>
              <Select placeholder="请选择是否有无线网络" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
      <DormitoryBuildingSelector visible={dormitoryBuildingSelectorVisible} onDormitoryBuildingSelected={handleDormitoryBuildingSelected} onCloseDormitoryBuildingSelector={handleCloseDormitoryBuildingSelector} />
    </Modal>
  )
}

export default DormitoryRoomAdd;
