// angular_ngzorro/src/app/dormitory-room/dormitory-room-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {DormitoryRoom} from '../../types/resp/DormitoryRoom';

@Component({
  selector: 'dormitory-room-view',
  imports: [
    SharedModule
  ],
  templateUrl: './dormitory-room-view.component.html',
  standalone: true
})
export class DormitoryRoomViewComponent implements OnInit {
  dormitoryRoomForm!: FormGroup;
  isVisible: boolean = false
  title: string = '宿舍房间信息详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.dormitoryRoomForm = this.fb.group({
      buildingName: [''],
      roomNumber: [''],
      floorNumber: [0],
      roomType: [undefined],
      availableBeds: [0],
      hasBathroom: [undefined],
      hasAirConditioning: [undefined],
      hasWifi: [undefined],
      createTime: [''],
      modifyTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(dormitoryRoom: DormitoryRoom) {
    this.isVisible = true
    this.dormitoryRoomForm.patchValue(dormitoryRoom);
    this.dormitoryRoomForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryRoomForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="buildingName">楼栋名称</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="buildingName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房间号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="floorNumber">所在楼层</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="floorNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomType">房间类型</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="roomType">
                <nz-option nzLabel="双人间" [nzValue]="2"></nz-option>
                <nz-option nzLabel="四人间" [nzValue]="4"></nz-option>
                <nz-option nzLabel="六人间" [nzValue]="6"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="availableBeds">可用床位</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="availableBeds" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="hasBathroom">是否有独立卫生间</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="hasBathroom">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="hasAirConditioning">是否有空调</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="hasAirConditioning">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="hasWifi">是否有无线网络</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="hasWifi">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="modifyTime">最后修改时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="modifyTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/dormitoryRoom/DormitoryRoomView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {DormitoryRoom} from "@/types/resp/dormitoryRoom";

interface DormitoryRoomViewProps {
  visible: boolean;
  viewRow: object;
  onCloseDormitoryRoomView: () => void;
}

const DormitoryRoomView: React.FC<DormitoryRoomViewProps> = ({visible, viewRow, onCloseDormitoryRoomView}) => {

  const [form] = Form.useForm<DormitoryRoom>();

  const onBack = () => {
    onCloseDormitoryRoomView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"宿舍房间信息详情"} open={visible} onCancel={onCloseDormitoryRoomView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="buildingName" label="楼栋名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="floorNumber" label="所在楼层">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomType" label="房间类型">
              <Select placeholder="请选择房间类型" options={[
                { value: 2, label: <span>双人间</span> },
                { value: 4, label: <span>四人间</span> },
                { value: 6, label: <span>六人间</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="availableBeds" label="可用床位">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="hasBathroom" label="是否有独立卫生间">
              <Select placeholder="请选择是否有独立卫生间" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="hasAirConditioning" label="是否有空调">
              <Select placeholder="请选择是否有空调" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="hasWifi" label="是否有无线网络">
              <Select placeholder="请选择是否有无线网络" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default DormitoryRoomView;
