// v2_el/src/views/roomMaintenanceRecord/RoomMaintenanceRecordList.vue
<template>
  <div class="room-maintenance-record-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>房间维护信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="searchParams">
      <el-form-item label="房间号" prop="roomNumber">
        <el-input v-model="searchParams.roomNumber" placeholder="请选择房间号" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryRoom"></i>
        </el-input>
      </el-form-item>
      <el-form-item label="员工姓名" prop="staffName">
        <el-input v-model="searchParams.staffName" placeholder="请选择员工姓名" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findStaff"></i>
        </el-input>
      </el-form-item>
      <el-form-item label="员工联系电话" prop="staffPhone">
        <el-input v-model="searchParams.staffPhone" placeholder="请选择员工联系电话" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findStaff"></i>
        </el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="pageData.list"
      border
      v-loading="pageData.loading"
      size="mini"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="roomNumber" label="房间号"></el-table-column>
      <el-table-column prop="staffName" label="员工姓名"></el-table-column>
      <el-table-column prop="staffPhone" label="员工联系电话"></el-table-column>
      <el-table-column prop="startTime" label="开始时间"></el-table-column>
      <el-table-column prop="endTime" label="结束时间"></el-table-column>
      <el-table-column prop="content" label="维护内容"></el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="paginationChange"
        :current-page="pageData.current"
        :page-sizes="pageData.pageSizes"
        :page-size="pageData.size"
        background
        layout="total, prev, pager, next, jumper"
        :total="pageData.count">
      </el-pagination>
    </div>
    <el-dialog :visible.sync="dormitoryRoomSelectorVisible" v-if="dormitoryRoomSelectorVisible" title="宿舍房间信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <dormitory-room-selector @dormitory-room-selected-event="handleDormitoryRoomSelectedEvent">
      </dormitory-room-selector>
    </el-dialog>
    <el-dialog :visible.sync="staffSelectorVisible" v-if="staffSelectorVisible" title="员工信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <staff-selector @staff-selected-event="handleStaffSelectedEvent">
      </staff-selector>
    </el-dialog>
    <el-dialog :visible.sync="roomMaintenanceRecordAddVisible" v-if="roomMaintenanceRecordAddVisible" :title="roomMaintenanceRecordAddTitle" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <room-maintenance-record-add :id="selectedRoomMaintenanceRecordId" @close-room-maintenance-record-add-event="handleCloseRoomMaintenanceRecordAddEvent" @reset-room-maintenance-record-add-event="handleResetRoomMaintenanceRecordAddEvent">
      </room-maintenance-record-add>
    </el-dialog>
    <el-dialog :visible.sync="roomMaintenanceRecordViewVisible" v-if="roomMaintenanceRecordViewVisible" title="房间维护信息详情" :top="dialogTop" :width="dialogWidth">
      <room-maintenance-record-view :id="selectedRoomMaintenanceRecordId" @close-room-maintenance-record-view-event="handleCloseRoomMaintenanceRecordViewEvent">
      </room-maintenance-record-view>
    </el-dialog>
  </div>
</template>

<script>
import roomMaintenanceRecordApi from '@/api/roomMaintenanceRecordApi'
import DormitoryRoomSelector from "@/views/dormitoryRoom/DormitoryRoomSelector.vue";
import StaffSelector from "@/views/staff/StaffSelector.vue";
import RoomMaintenanceRecordAdd from "@/views/roomMaintenanceRecord/RoomMaintenanceRecordAdd.vue"
import RoomMaintenanceRecordView from "@/views/roomMaintenanceRecord/RoomMaintenanceRecordView.vue"
import listQueryMixin from '@/mixins/listQueryMixin'
export default {
  name: 'RoomMaintenanceRecordList',
  components: {DormitoryRoomSelector,StaffSelector,RoomMaintenanceRecordAdd, RoomMaintenanceRecordView},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        roomId: '',
        roomNumber: '',
        staffId: '',
        staffName: '',
        staffPhone: '',
      },
      dormitoryRoomSelectorVisible: false,
      staffSelectorVisible: false,
      roomMaintenanceRecordAddVisible: false,
      roomMaintenanceRecordAddTitle: '',
      roomMaintenanceRecordViewVisible: false,
      selectedRoomMaintenanceRecordId: 0
    }
  },
  methods: {
    getPageData (p) {
      return roomMaintenanceRecordApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        roomId: '',
        roomNumber: '',
        staffId: '',
        staffName: '',
        staffPhone: '',
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    onAdd () {
      this.selectedRoomMaintenanceRecordId = ''
      this.roomMaintenanceRecordAddVisible = true
      this.roomMaintenanceRecordAddTitle = '房间维护信息新增'
    },
    editRow (id) {
      this.selectedRoomMaintenanceRecordId = id
      this.roomMaintenanceRecordAddVisible = true
      this.roomMaintenanceRecordAddTitle = '房间维护信息编辑'
    },
    delRow (id) {
      if (!id) {
        return
      }
      this.$confirm('确定要删除吗?', '删除提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        roomMaintenanceRecordApi.del(id)
          .then((resp) => {
            if (resp && resp.code === 1) {
              this.$message.success('删除成功!')
              this.onSearch()
            } else {
              this.$message.error('删除失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          })
          .catch(error => {
            console.error('操作失败:', error)
          })
      }).catch(() => {})
    },
    detailRow (id) {
      this.selectedRoomMaintenanceRecordId = id
      this.roomMaintenanceRecordViewVisible = true
    },
    findDormitoryRoom () {
      this.dormitoryRoomSelectorVisible = true
    },
    handleDormitoryRoomSelectedEvent (selectedDormitoryRoom) {
      this.dormitoryRoomSelectorVisible = false
      if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom && this.searchParams.roomId !== selectedDormitoryRoom['roomId']) {
        this.searchParams.roomId = selectedDormitoryRoom['roomId']
        this.searchParams.roomNumber = selectedDormitoryRoom['roomNumber']
      }
    },
    findStaff () {
      this.staffSelectorVisible = true
    },
    handleStaffSelectedEvent (selectedStaff) {
      this.staffSelectorVisible = false
      if (selectedStaff && 'staffId' in selectedStaff && this.searchParams.staffId !== selectedStaff['staffId']) {
        this.searchParams.staffId = selectedStaff['staffId']
        this.searchParams.staffName = selectedStaff['staffName']
        this.searchParams.staffPhone = selectedStaff['staffPhone']
      }
    },
    handleCloseRoomMaintenanceRecordViewEvent () {
      this.roomMaintenanceRecordViewVisible = false
    },
    handleResetRoomMaintenanceRecordAddEvent () {
      this.roomMaintenanceRecordAddTitle = '房间维护信息新增'
    },
    handleCloseRoomMaintenanceRecordAddEvent (params) {
      if (params && params.search) {
        this.onSearch()
      }
      this.roomMaintenanceRecordAddVisible = false
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/roomMaintenanceRecord/RoomMaintenanceRecordList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {RoomMaintenanceRecord} from "@/types/resp/roomMaintenanceRecord";
import roomMaintenanceRecordApi from '@/api/roomMaintenanceRecordApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import RoomMaintenanceRecordAdd from "@/pages/roomMaintenanceRecord/RoomMaintenanceRecordAdd.tsx";
import RoomMaintenanceRecordView from "@/pages/roomMaintenanceRecord/RoomMaintenanceRecordView.tsx";
import DormitoryRoomSelector from "@/pages/dormitoryRoom/DormitoryRoomSelector.tsx";
import StaffSelector from "@/pages/staff/StaffSelector.tsx";


const RoomMaintenanceRecordList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '房间维护信息列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<RoomMaintenanceRecord[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<RoomMaintenanceRecord>> = await roomMaintenanceRecordApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<RoomMaintenanceRecord> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<RoomMaintenanceRecord>['columns'] = [
    {title: '房间号', dataIndex: 'roomNumber', key: 'roomNumber'},
    {title: '员工姓名', dataIndex: 'staffName', key: 'staffName'},
    {title: '员工联系电话', dataIndex: 'staffPhone', key: 'staffPhone'},
    {title: '开始时间', key: 'startTime', render: (_, record) => (
      <div>{record.startTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '结束时间', key: 'endTime', render: (_, record) => (
      <div>{record.endTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '维护内容', dataIndex: 'content', key: 'content', ellipsis: true},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [roomMaintenanceRecordAddVisible, setRoomMaintenanceRecordAddVisible] = useState(false);
  const [roomMaintenanceRecordViewVisible, setRoomMaintenanceRecordViewVisible] = useState(false);
  const [selectedRoomMaintenanceRecordId, setSelectedRoomMaintenanceRecordId] = useState(0)
  const [selectedRoomMaintenanceRecord, setSelectedRoomMaintenanceRecord] = useState({})

  const onAdd = () => {
    setSelectedRoomMaintenanceRecordId(0)
    setRoomMaintenanceRecordAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedRoomMaintenanceRecordId(id)
    setRoomMaintenanceRecordAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      roomMaintenanceRecordApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: RoomMaintenanceRecord) => {
    setSelectedRoomMaintenanceRecord(record)
    setRoomMaintenanceRecordViewVisible(true)
  };

  const [dormitoryRoomSelectorVisible, setDormitoryRoomSelectorVisible] = useState(false);
  const findDormitoryRoom = () => {
    setDormitoryRoomSelectorVisible(true);
  }
  const handleDormitoryRoomSelected = (selectedDormitoryRoom: { roomId?: number; roomNumber?: string; }) => {
    setDormitoryRoomSelectorVisible(false)
    if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      roomId: selectedDormitoryRoom['roomId'],
      roomNumber: selectedDormitoryRoom['roomNumber'],
      }));
    }
  };
  const handleCloseDormitoryRoomSelector = () => {
    setDormitoryRoomSelectorVisible(false)
  };
  const [staffSelectorVisible, setStaffSelectorVisible] = useState(false);
  const findStaff = () => {
    setStaffSelectorVisible(true);
  }
  const handleStaffSelected = (selectedStaff: { staffId?: number; staffName?: string; staffPhone?: string; }) => {
    setStaffSelectorVisible(false)
    if (selectedStaff && 'staffId' in selectedStaff) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      staffId: selectedStaff['staffId'],
      staffName: selectedStaff['staffName'],
      staffPhone: selectedStaff['staffPhone'],
      }));
    }
  };
  const handleCloseStaffSelector = () => {
    setStaffSelectorVisible(false)
  };

  const handleCloseRoomMaintenanceRecordAdd = () => {
    setRoomMaintenanceRecordAddVisible(false)
  };

  const handleCloseRoomMaintenanceRecordView = () => {
    setRoomMaintenanceRecordViewVisible(false)
  };

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="roomMaintenanceRecordList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="roomNumber" label="房间号">
          <Input.Search placeholder="请选择房间号" onSearch={findDormitoryRoom} readOnly={true} />
        </Form.Item>
        <Form.Item name="staffName" label="员工姓名">
          <Input.Search placeholder="请选择员工姓名" onSearch={findStaff} readOnly={true} />
        </Form.Item>
        <Form.Item name="staffPhone" label="员工联系电话">
          <Input.Search placeholder="请选择员工联系电话" onSearch={findStaff} readOnly={true} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
      </Form>
      <Table<RoomMaintenanceRecord> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <DormitoryRoomSelector visible={dormitoryRoomSelectorVisible} onDormitoryRoomSelected={handleDormitoryRoomSelected} onCloseDormitoryRoomSelector={handleCloseDormitoryRoomSelector} />
      <StaffSelector visible={staffSelectorVisible} onStaffSelected={handleStaffSelected} onCloseStaffSelector={handleCloseStaffSelector} />
      <RoomMaintenanceRecordAdd visible={roomMaintenanceRecordAddVisible} onCloseRoomMaintenanceRecordAdd={handleCloseRoomMaintenanceRecordAdd} id={selectedRoomMaintenanceRecordId} />
      <RoomMaintenanceRecordView visible={roomMaintenanceRecordViewVisible} onCloseRoomMaintenanceRecordView={handleCloseRoomMaintenanceRecordView} viewRow={selectedRoomMaintenanceRecord} />
    </div>
  );
};

export default RoomMaintenanceRecordList;
