// angular_ngzorro/src/app/dormitory-building/dormitory-building-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {DormitoryBuildingService} from '../../service/dormitory-building.service';
import {SharedModule} from '../shared.module';
import {DormitoryBuildingForm} from '../../types/req/DormitoryBuildingForm';
import {MODAL_WIDTH} from '../../const'
import {StaffSelectorComponent} from '../staff/staff-selector.component';

@Component({
  selector: 'dormitory-building-add',
  imports: [
    StaffSelectorComponent,
    SharedModule
  ],
  templateUrl: './dormitory-building-add.component.html',
  standalone: true
})
export class DormitoryBuildingAddComponent implements OnInit {
  dormitoryBuildingToSave:DormitoryBuildingForm = {};
  dormitoryBuildingForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增宿舍楼栋信息'
  modalWidth: string = MODAL_WIDTH
  

  @ViewChild(StaffSelectorComponent, { static: false }) staffSelectorComponent!: StaffSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private dormitoryBuildingService: DormitoryBuildingService
  ) {}

  ngOnInit(): void {
    this.dormitoryBuildingForm = this.fb.group({
      name: ['', [Validators.required]],
      constructionYear: [0],
      floorNumber: [0, [Validators.required]],
      buildingType: [undefined, [Validators.required]],
      staffId: [0],
      staffName: ['', [Validators.required]],
      buildingLocation: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.dormitoryBuildingForm.controls) {
        this.dormitoryBuildingForm.controls[i].markAsDirty();
        this.dormitoryBuildingForm.controls[i].updateValueAndValidity();
      }
      if (!this.dormitoryBuildingForm.valid) {
        this.saveLoading = false
        return
      }
      this.dormitoryBuildingService.save(Object.assign(this.dormitoryBuildingToSave, this.dormitoryBuildingForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增宿舍楼栋信息'.slice()
    this.dormitoryBuildingForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改宿舍楼栋信息'
      this.saveLoading = true
      this.dormitoryBuildingService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.dormitoryBuildingToSave = resp.data
            this.dormitoryBuildingForm.patchValue(this.dormitoryBuildingToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findStaff() {
    this.staffSelectorComponent.display()
  }

  handleStaffSelectedEvent(selectedStaff: { staffId?: number; staffName?: string; }) {
    if (selectedStaff && 'staffId' in selectedStaff) {
      this.dormitoryBuildingForm.patchValue(selectedStaff);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryBuildingForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>楼栋名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入楼栋名称'">
              <input nz-input formControlName="name" placeholder="请输入楼栋名称" maxlength="32"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="constructionYear">建筑年份</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="constructionYear" nzMin="1" nzMax="2100" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="floorNumber" nzRequired>楼层</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择楼层'">
            <nz-input-number formControlName="floorNumber" nzMin="1" nzMax="127" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="buildingType" nzRequired>楼栋类型</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择楼栋类型'">
              <nz-select formControlName="buildingType">
                <nz-option nzLabel="男生" [nzValue]="1"></nz-option>
                <nz-option nzLabel="女生" [nzValue]="2"></nz-option>
                <nz-option nzLabel="按楼层男女混住" [nzValue]="3"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="staffName" nzRequired>宿管姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择宿管姓名'">
              <nz-input-group nzSearch [nzAddOnAfter]="suffixIconButton">
                <input nz-input formControlName="staffName" placeholder="请选择宿管姓名" readonly />
              </nz-input-group>
              <ng-template #suffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findStaff()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="buildingLocation">位置</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="buildingLocation" placeholder="请输入位置" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<staff-selector (staffSelectedEvent)="handleStaffSelectedEvent($event)"></staff-selector>

// v2_el/src/views/dormitoryBuilding/DormitoryBuildingAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryBuildingForm" :label-width="formLabelWidth" ref="refDormitoryBuildingForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼栋名称" prop="name">
            <el-input v-model="dormitoryBuildingForm.name" placeholder="请输入楼栋名称" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="建筑年份" prop="constructionYear">
            <el-input-number v-model="dormitoryBuildingForm.constructionYear" :min="1" :max="1"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼层" prop="floorNumber">
            <el-input-number v-model="dormitoryBuildingForm.floorNumber" :min="1" :max="127"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="楼栋类型" prop="buildingType">
            <el-select v-model="dormitoryBuildingForm.buildingType" placeholder="请选择楼栋类型">
              <el-option label="男生" :value="1"></el-option>
              <el-option label="女生" :value="2"></el-option>
              <el-option label="按楼层男女混住" :value="3"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="宿管姓名" prop="staffName">
            <el-input v-model="dormitoryBuildingForm.staffName" placeholder="请选择宿管姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStaff"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="位置" prop="buildingLocation">
            <el-input v-model="dormitoryBuildingForm.buildingLocation" placeholder="请输入位置" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="staffSelectorVisible" v-if="staffSelectorVisible" title="员工信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <staff-selector @staff-selected-event="handleStaffSelectedEvent">
      </staff-selector>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryBuildingApi from '@/api/dormitoryBuildingApi'
import StaffSelector from "@/views/staff/StaffSelector.vue";
export default {
  name: 'DormitoryBuildingAdd',
  components: {StaffSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryBuildingForm: {
        name: '',
        constructionYear: '',
        floorNumber: '',
        buildingType: '',
        staffId: '',
        staffName: '',
        buildingLocation: ''
      },
      rules: {
        name: [
          { required: true, message: '请输入楼栋名称', trigger: 'blur' }
        ],
        floorNumber: [
          { required: true, message: '请输入楼层', trigger: 'blur' }
        ],
        buildingType: [
          { required: true, message: '请输入楼栋类型', trigger: 'blur' }
        ],
        staffName: [
          { required: true, message: '请输入宿管姓名', trigger: 'blur' }
        ],
      },
      staffSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      dormitoryBuildingApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.dormitoryBuildingForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.dormitoryBuildingForm = {
        name: '',
        constructionYear: '',
        floorNumber: '',
        buildingType: '',
        staffId: '',
        staffName: '',
        buildingLocation: ''
      }
      this.$emit('reset-dormitory-building-add-event')
    },
    onSave () {
      this.$refs.refDormitoryBuildingForm.validate((valid) => {
        if (valid) {
          dormitoryBuildingApi.save(this.dormitoryBuildingForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-dormitory-building-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findStaff () {
      this.staffSelectorVisible = true
    },
    handleStaffSelectedEvent (selectedStaff) {
      this.staffSelectorVisible = false
      if (selectedStaff && 'staffId' in selectedStaff && this.dormitoryBuildingForm.staffId !== selectedStaff['staffId']) {
        this.dormitoryBuildingForm.staffId = selectedStaff['staffId']
        this.dormitoryBuildingForm.staffName = selectedStaff['staffName']
      }
    },
    onBack () {
      this.$emit('close-dormitory-building-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
