// react_antd/src/pages/dormitoryVisitor/DormitoryVisitorView.tsx
import React, {useEffect} from "react";
import {Button, Col, DatePicker, Form, Input, Modal, Row} from "antd";
import {DormitoryVisitor} from "@/types/resp/dormitoryVisitor";

interface DormitoryVisitorViewProps {
  visible: boolean;
  viewRow: object;
  onCloseDormitoryVisitorView: () => void;
}

const DormitoryVisitorView: React.FC<DormitoryVisitorViewProps> = ({visible, viewRow, onCloseDormitoryVisitorView}) => {

  const [form] = Form.useForm<DormitoryVisitor>();

  const onBack = () => {
    onCloseDormitoryVisitorView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"访客记录详情"} open={visible} onCancel={onCloseDormitoryVisitorView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="studentName" label="学生姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="visitorName" label="访客姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="contactPhone" label="访客联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="visitStartTime" label="开始时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="visitEndTime" label="结束时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default DormitoryVisitorView;

// angular_ngzorro/src/app/dormitory-visitor/dormitory-visitor-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {DormitoryVisitor} from '../../types/resp/DormitoryVisitor';

@Component({
  selector: 'dormitory-visitor-view',
  imports: [
    SharedModule
  ],
  templateUrl: './dormitory-visitor-view.component.html',
  standalone: true
})
export class DormitoryVisitorViewComponent implements OnInit {
  dormitoryVisitorForm!: FormGroup;
  isVisible: boolean = false
  title: string = '访客记录详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.dormitoryVisitorForm = this.fb.group({
      roomNumber: [''],
      studentName: [''],
      visitorName: [''],
      contactPhone: [''],
      visitStartTime: [''],
      visitEndTime: [''],
      createTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(dormitoryVisitor: DormitoryVisitor) {
    this.isVisible = true
    this.dormitoryVisitorForm.patchValue(dormitoryVisitor);
    this.dormitoryVisitorForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryVisitorForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房间号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentName">学生姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="studentName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="visitorName">访客姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="visitorName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone">访客联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="contactPhone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="visitStartTime">开始时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="visitStartTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="visitEndTime">结束时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="visitEndTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
