// v2_el/src/views/dormitoryVisitor/DormitoryVisitorView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryVisitorForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房间号">
            <el-input v-model="dormitoryVisitorForm.roomNumber"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名">
            <el-input v-model="dormitoryVisitorForm.studentName"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="访客姓名">
            <el-input v-model="dormitoryVisitorForm.visitorName"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="访客联系电话">
            <el-input v-model="dormitoryVisitorForm.contactPhone"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="开始时间">
            <el-input v-model="dormitoryVisitorForm.visitStartTime"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="结束时间">
            <el-input v-model="dormitoryVisitorForm.visitEndTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="dormitoryVisitorForm.createTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import dormitoryVisitorApi from '@/api/dormitoryVisitorApi'
export default {
  name: 'DormitoryVisitorView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryVisitorForm: {
      }
    }
  },
  created () {
    if (this.id) {
      dormitoryVisitorApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.dormitoryVisitorForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-dormitory-visitor-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/dormitoryVisitor/DormitoryVisitorView.tsx
import React, {useEffect} from "react";
import {Button, Col, DatePicker, Form, Input, Modal, Row} from "antd";
import {DormitoryVisitor} from "@/types/resp/dormitoryVisitor";

interface DormitoryVisitorViewProps {
  visible: boolean;
  viewRow: object;
  onCloseDormitoryVisitorView: () => void;
}

const DormitoryVisitorView: React.FC<DormitoryVisitorViewProps> = ({visible, viewRow, onCloseDormitoryVisitorView}) => {

  const [form] = Form.useForm<DormitoryVisitor>();

  const onBack = () => {
    onCloseDormitoryVisitorView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"访客记录详情"} open={visible} onCancel={onCloseDormitoryVisitorView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房间号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="studentName" label="学生姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="visitorName" label="访客姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="contactPhone" label="访客联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="visitStartTime" label="开始时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="visitEndTime" label="结束时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default DormitoryVisitorView;
