// angular_ngzorro/src/app/dormitory-building/dormitory-building-selector.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {DormitoryBuildingService} from '../../service/dormitory-building.service';
import {DormitoryBuildingQueryForm} from '../../types/req/DormitoryBuildingQueryForm';
import {SharedModule} from '../shared.module';
import {DormitoryBuilding} from '../../types/resp/DormitoryBuilding';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';
import {StaffSelectorComponent} from '../staff/staff-selector.component';

@Component({
  selector: 'dormitory-building-selector',
  imports: [
    StaffSelectorComponent,
    SharedModule
  ],
  templateUrl: './dormitory-building-selector.component.html',
  standalone: true
})
export class DormitoryBuildingSelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: DormitoryBuilding[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '宿舍楼栋信息选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(StaffSelectorComponent, { static: false }) staffSelectorComponent!: StaffSelectorComponent;

  @Output() dormitoryBuildingSelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private dormitoryBuildingService: DormitoryBuildingService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      name: [''],
      buildingType: [undefined],
      staffId: [0],
      staffName: [''],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.dormitoryBuildingService.find(new DormitoryBuildingQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<DormitoryBuilding> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: DormitoryBuilding, event: MouseEvent) {
    this.isVisible = false
    this.dormitoryBuildingSelectedEvent.emit({
      buildingId: row.id,
      buildingName: row.name,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

  findStaff() {
    this.staffSelectorComponent.display()
  }

  handleStaffSelectedEvent(selectedStaff: { staffId?: number; staffName?: string; }) {
    if (selectedStaff && 'staffId' in selectedStaff) {
      this.searchForm.patchValue(selectedStaff);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="onSearch()" nzLayout="inline">
      <nz-form-item>
        <nz-form-label nzFor="name">楼栋名称</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="name" placeholder="请输入楼栋名称" />
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="buildingType">楼栋类型</nz-form-label>
        <nz-form-control>
          <nz-select formControlName="buildingType" class="custom-select-width">
            <nz-option nzLabel="男生" [nzValue]="1"></nz-option>
            <nz-option nzLabel="女生" [nzValue]="2"></nz-option>
            <nz-option nzLabel="按楼层男女混住" [nzValue]="3"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="staffName">宿管姓名</nz-form-label>
        <nz-form-control>
          <nz-input-group nzSearch [nzAddOnAfter]="suffixIconButton">
            <input nz-input formControlName="staffName" placeholder="请选择宿管姓名" readonly />
          </nz-input-group>
          <ng-template #suffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findStaff()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
      <thead>
        <tr>
          <th>楼栋名称</th>
          <th>建筑年份</th>
          <th>楼层</th>
          <th>楼栋类型</th>
          <th>宿管姓名</th>
          <th>位置</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.name}}</td>
          <td>{{data.constructionYear}}</td>
          <td>{{data.floorNumber}}</td>
          <td>
            <ng-container *ngIf="data.buildingType === 1">男生</ng-container>
            <ng-container *ngIf="data.buildingType === 2">女生</ng-container>
            <ng-container *ngIf="data.buildingType === 3">按楼层男女混住</ng-container>
          </td>
          <td>{{data.staffName}}</td>
          <td>{{data.buildingLocation}}</td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<staff-selector (staffSelectedEvent)="handleStaffSelectedEvent($event)"></staff-selector>

// react_antd/src/pages/dormitoryBuilding/DormitoryBuildingSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Select, Table, TableProps} from 'antd';
import type {DormitoryBuilding} from "@/types/resp/dormitoryBuilding";
import dormitoryBuildingApi from '@/api/dormitoryBuildingApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import StaffSelector from "@/pages/staff/StaffSelector.tsx";


interface DormitoryBuildingSelectorProps {
  visible: boolean;
  onDormitoryBuildingSelected: (selectedDormitoryBuilding: { buildingId?: number; buildingName?: string; }) => void;
  onCloseDormitoryBuildingSelector: () => void;
}

const DormitoryBuildingSelector: React.FC<DormitoryBuildingSelectorProps> = ({visible, onDormitoryBuildingSelected, onCloseDormitoryBuildingSelector}) => {

  const [dormitoryBuildingSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    dormitoryBuildingSelectorForm.resetFields();
  };

  const [data, setData] = useState<DormitoryBuilding[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<DormitoryBuilding>> = await dormitoryBuildingApi.find(dormitoryBuildingSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<DormitoryBuilding> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<DormitoryBuilding>['columns'] = [
    {title: '楼栋名称', dataIndex: 'name', key: 'name'},
    {title: '建筑年份', dataIndex: 'constructionYear', key: 'constructionYear'},
    {title: '楼层', dataIndex: 'floorNumber', key: 'floorNumber'},
    {title: '楼栋类型', key: 'buildingType', render: (_, record) => (
        <span>
        {(function () {
          if (record.buildingType === 1) return '男生';
          else if (record.buildingType === 2) return '女生';
          else if (record.buildingType === 3) return '按楼层男女混住';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '宿管姓名', dataIndex: 'staffName', key: 'staffName'},
    {title: '位置', dataIndex: 'buildingLocation', key: 'buildingLocation'},
  ];

  const handleRowDoubleClick = (row: DormitoryBuilding) => {
    onDormitoryBuildingSelected({
      buildingId: row.id,
      buildingName: row.name,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseDormitoryBuildingSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);

  const [staffSelectorVisible, setStaffSelectorVisible] = useState(false);
  const findStaff = () => {
    setStaffSelectorVisible(true);
  }
  const handleStaffSelected = (selectedStaff: { staffId?: number; staffName?: string; }) => {
    setStaffSelectorVisible(false)
    if (selectedStaff && 'staffId' in selectedStaff) {
      dormitoryBuildingSelectorForm.setFieldsValue(Object.assign(dormitoryBuildingSelectorForm.getFieldsValue(), {
      staffId: selectedStaff['staffId'],
      staffName: selectedStaff['staffName'],
      }));
    }
  };
  const handleCloseStaffSelector = () => {
    setStaffSelectorVisible(false)
  };

  return (
    <Modal title={"宿舍楼栋信息选择器(双击行选中)"} open={visible} onCancel={onCloseDormitoryBuildingSelector}
        width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={dormitoryBuildingSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="楼栋名称">
          <Input maxLength={32} placeholder="请输入楼栋名称"/>
        </Form.Item>
        <Form.Item name="buildingType" label="楼栋类型">
          <Select placeholder="请选择楼栋类型" options={[
            { value: 1, label: <span>男生</span> },
            { value: 2, label: <span>女生</span> },
            { value: 3, label: <span>按楼层男女混住</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<DormitoryBuilding> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
      <StaffSelector visible={staffSelectorVisible} onStaffSelected={handleStaffSelected} onCloseStaffSelector={handleCloseStaffSelector} />
    </Modal>
  );
};

export default DormitoryBuildingSelector;
