// v2_el/src/views/dormitoryBuilding/DormitoryBuildingView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryBuildingForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼栋名称">
            <el-input v-model="dormitoryBuildingForm.name"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="建筑年份">
            <el-input v-model="dormitoryBuildingForm.constructionYear"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼层">
            <el-input v-model="dormitoryBuildingForm.floorNumber"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="楼栋类型">
            <el-select v-model="dormitoryBuildingForm.buildingType" placeholder="请选择楼栋类型">
              <el-option label="男生" :value="1"></el-option>
              <el-option label="女生" :value="2"></el-option>
              <el-option label="按楼层男女混住" :value="3"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="姓名">
            <el-input v-model="dormitoryBuildingForm.staffName"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="位置">
            <el-input v-model="dormitoryBuildingForm.buildingLocation"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="dormitoryBuildingForm.createTime"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="最后修改时间">
            <el-input v-model="dormitoryBuildingForm.modifyTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import dormitoryBuildingApi from '@/api/dormitoryBuildingApi'
export default {
  name: 'DormitoryBuildingView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryBuildingForm: {
      }
    }
  },
  created () {
    if (this.id) {
      dormitoryBuildingApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.dormitoryBuildingForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-dormitory-building-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/dormitoryBuilding/DormitoryBuildingView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {DormitoryBuilding} from "@/types/resp/dormitoryBuilding";

interface DormitoryBuildingViewProps {
  visible: boolean;
  viewRow: object;
  onCloseDormitoryBuildingView: () => void;
}

const DormitoryBuildingView: React.FC<DormitoryBuildingViewProps> = ({visible, viewRow, onCloseDormitoryBuildingView}) => {

  const [form] = Form.useForm<DormitoryBuilding>();

  const onBack = () => {
    onCloseDormitoryBuildingView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"宿舍楼栋信息详情"} open={visible} onCancel={onCloseDormitoryBuildingView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="楼栋名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="constructionYear" label="建筑年份">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="floorNumber" label="楼层">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="buildingType" label="楼栋类型">
              <Select placeholder="请选择楼栋类型" options={[
                { value: 1, label: <span>男生</span> },
                { value: 2, label: <span>女生</span> },
                { value: 3, label: <span>按楼层男女混住</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="staffName" label="宿管姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="buildingLocation" label="位置">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default DormitoryBuildingView;
