// v2_el/src/views/dormitoryRoom/DormitoryRoomAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryRoomForm" :label-width="formLabelWidth" ref="refDormitoryRoomForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼栋名称" prop="buildingName">
            <el-input v-model="dormitoryRoomForm.buildingName" placeholder="请选择楼栋名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryBuilding"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房间号" prop="roomNumber">
            <el-input v-model="dormitoryRoomForm.roomNumber" placeholder="请输入房间号" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="所在楼层" prop="floorNumber">
            <el-input-number v-model="dormitoryRoomForm.floorNumber" :min="1" :max="128"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房间类型" prop="roomType">
            <el-select v-model="dormitoryRoomForm.roomType" placeholder="请选择房间类型">
              <el-option label="双人间" :value="2"></el-option>
              <el-option label="四人间" :value="4"></el-option>
              <el-option label="六人间" :value="6"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有独立卫生间" prop="hasBathroom">
            <el-select v-model="dormitoryRoomForm.hasBathroom" placeholder="请选择是否有独立卫生间">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有空调" prop="hasAirConditioning">
            <el-select v-model="dormitoryRoomForm.hasAirConditioning" placeholder="请选择是否有空调">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有无线网络" prop="hasWifi">
            <el-select v-model="dormitoryRoomForm.hasWifi" placeholder="请选择是否有无线网络">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="dormitoryBuildingSelectorVisible" v-if="dormitoryBuildingSelectorVisible" title="宿舍楼栋信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <dormitory-building-selector @dormitory-building-selected-event="handleDormitoryBuildingSelectedEvent">
      </dormitory-building-selector>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryRoomApi from '@/api/dormitoryRoomApi'
import DormitoryBuildingSelector from "@/views/dormitoryBuilding/DormitoryBuildingSelector.vue";
export default {
  name: 'DormitoryRoomAdd',
  components: {DormitoryBuildingSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryRoomForm: {
        buildingId: '',
        buildingName: '',
        roomNumber: '',
        floorNumber: '',
        roomType: '',
        hasBathroom: '',
        hasAirConditioning: '',
        hasWifi: ''
      },
      rules: {
        buildingName: [
          { required: true, message: '请输入楼栋名称', trigger: 'blur' }
        ],
        roomNumber: [
          { required: true, message: '请输入房间号', trigger: 'blur' }
        ],
        floorNumber: [
          { required: true, message: '请输入所在楼层', trigger: 'blur' }
        ],
        roomType: [
          { required: true, message: '请输入房间类型', trigger: 'blur' }
        ],
        hasBathroom: [
          { required: true, message: '请输入是否有独立卫生间', trigger: 'blur' }
        ],
        hasAirConditioning: [
          { required: true, message: '请输入是否有空调', trigger: 'blur' }
        ],
        hasWifi: [
          { required: true, message: '请输入是否有无线网络', trigger: 'blur' }
        ],
      },
      dormitoryBuildingSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      dormitoryRoomApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.dormitoryRoomForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.dormitoryRoomForm = {
        buildingId: '',
        buildingName: '',
        roomNumber: '',
        floorNumber: '',
        roomType: '',
        hasBathroom: '',
        hasAirConditioning: '',
        hasWifi: ''
      }
      this.$emit('reset-dormitory-room-add-event')
    },
    onSave () {
      this.$refs.refDormitoryRoomForm.validate((valid) => {
        if (valid) {
          dormitoryRoomApi.save(this.dormitoryRoomForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-dormitory-room-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findDormitoryBuilding () {
      this.dormitoryBuildingSelectorVisible = true
    },
    handleDormitoryBuildingSelectedEvent (selectedDormitoryBuilding) {
      this.dormitoryBuildingSelectorVisible = false
      if (selectedDormitoryBuilding && 'buildingId' in selectedDormitoryBuilding && this.dormitoryRoomForm.buildingId !== selectedDormitoryBuilding['buildingId']) {
        this.dormitoryRoomForm.buildingId = selectedDormitoryBuilding['buildingId']
        this.dormitoryRoomForm.buildingName = selectedDormitoryBuilding['buildingName']
      }
    },
    onBack () {
      this.$emit('close-dormitory-room-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/dormitory-room/dormitory-room-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {DormitoryRoomService} from '../../service/dormitory-room.service';
import {SharedModule} from '../shared.module';
import {DormitoryRoomForm} from '../../types/req/DormitoryRoomForm';
import {MODAL_WIDTH} from '../../const'
import {DormitoryBuildingSelectorComponent} from '../dormitory-building/dormitory-building-selector.component';

@Component({
  selector: 'dormitory-room-add',
  imports: [
    DormitoryBuildingSelectorComponent,
    SharedModule
  ],
  templateUrl: './dormitory-room-add.component.html',
  standalone: true
})
export class DormitoryRoomAddComponent implements OnInit {
  dormitoryRoomToSave:DormitoryRoomForm = {};
  dormitoryRoomForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增宿舍房间信息'
  modalWidth: string = MODAL_WIDTH
  

  @ViewChild(DormitoryBuildingSelectorComponent, { static: false }) dormitoryBuildingSelectorComponent!: DormitoryBuildingSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private dormitoryRoomService: DormitoryRoomService
  ) {}

  ngOnInit(): void {
    this.dormitoryRoomForm = this.fb.group({
      buildingId: [0],
      buildingName: ['', [Validators.required]],
      roomNumber: ['', [Validators.required]],
      floorNumber: [0, [Validators.required]],
      roomType: [undefined, [Validators.required]],
      hasBathroom: [undefined, [Validators.required]],
      hasAirConditioning: [undefined, [Validators.required]],
      hasWifi: [undefined, [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.dormitoryRoomForm.controls) {
        this.dormitoryRoomForm.controls[i].markAsDirty();
        this.dormitoryRoomForm.controls[i].updateValueAndValidity();
      }
      if (!this.dormitoryRoomForm.valid) {
        this.saveLoading = false
        return
      }
      this.dormitoryRoomService.save(Object.assign(this.dormitoryRoomToSave, this.dormitoryRoomForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增宿舍房间信息'.slice()
    this.dormitoryRoomForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改宿舍房间信息'
      this.saveLoading = true
      this.dormitoryRoomService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.dormitoryRoomToSave = resp.data
            this.dormitoryRoomForm.patchValue(this.dormitoryRoomToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findDormitoryBuilding() {
    this.dormitoryBuildingSelectorComponent.display()
  }

  handleDormitoryBuildingSelectedEvent(selectedDormitoryBuilding: { buildingId?: number; buildingName?: string; }) {
    if (selectedDormitoryBuilding && 'buildingId' in selectedDormitoryBuilding) {
      this.dormitoryRoomForm.patchValue(selectedDormitoryBuilding);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryRoomForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="buildingName" nzRequired>楼栋名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择楼栋名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="suffixIconButton">
                <input nz-input formControlName="buildingName" placeholder="请选择楼栋名称" readonly />
              </nz-input-group>
              <ng-template #suffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findDormitoryBuilding()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房间号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入房间号'">
              <input nz-input formControlName="roomNumber" placeholder="请输入房间号" maxlength="32"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="floorNumber" nzRequired>所在楼层</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择所在楼层'">
            <nz-input-number formControlName="floorNumber" nzMin="1" nzMax="128" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomType" nzRequired>房间类型</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房间类型'">
              <nz-select formControlName="roomType">
                <nz-option nzLabel="双人间" [nzValue]="2"></nz-option>
                <nz-option nzLabel="四人间" [nzValue]="4"></nz-option>
                <nz-option nzLabel="六人间" [nzValue]="6"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="hasBathroom" nzRequired>是否有独立卫生间</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择是否有独立卫生间'">
              <nz-select formControlName="hasBathroom">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="hasAirConditioning" nzRequired>是否有空调</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择是否有空调'">
              <nz-select formControlName="hasAirConditioning">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="hasWifi" nzRequired>是否有无线网络</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择是否有无线网络'">
              <nz-select formControlName="hasWifi">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<dormitory-building-selector (dormitoryBuildingSelectedEvent)="handleDormitoryBuildingSelectedEvent($event)"></dormitory-building-selector>
