// react_antd/src/pages/dormitoryBuilding/DormitoryBuildingSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Select, Table, TableProps} from 'antd';
import type {DormitoryBuilding} from "@/types/resp/dormitoryBuilding";
import dormitoryBuildingApi from '@/api/dormitoryBuildingApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import StaffSelector from "@/pages/staff/StaffSelector.tsx";


interface DormitoryBuildingSelectorProps {
  visible: boolean;
  onDormitoryBuildingSelected: (selectedDormitoryBuilding: { buildingId?: number; buildingName?: string; }) => void;
  onCloseDormitoryBuildingSelector: () => void;
}

const DormitoryBuildingSelector: React.FC<DormitoryBuildingSelectorProps> = ({visible, onDormitoryBuildingSelected, onCloseDormitoryBuildingSelector}) => {

  const [dormitoryBuildingSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    dormitoryBuildingSelectorForm.resetFields();
  };

  const [data, setData] = useState<DormitoryBuilding[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<DormitoryBuilding>> = await dormitoryBuildingApi.find(dormitoryBuildingSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<DormitoryBuilding> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<DormitoryBuilding>['columns'] = [
    {title: '楼栋名称', dataIndex: 'name', key: 'name'},
    {title: '建筑年份', dataIndex: 'constructionYear', key: 'constructionYear'},
    {title: '楼层', dataIndex: 'floorNumber', key: 'floorNumber'},
    {title: '楼栋类型', key: 'buildingType', render: (_, record) => (
        <span>
        {(function () {
          if (record.buildingType === 1) return '男生';
          else if (record.buildingType === 2) return '女生';
          else if (record.buildingType === 3) return '按楼层男女混住';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '宿管姓名', dataIndex: 'staffName', key: 'staffName'},
    {title: '位置', dataIndex: 'buildingLocation', key: 'buildingLocation'},
  ];

  const handleRowDoubleClick = (row: DormitoryBuilding) => {
    onDormitoryBuildingSelected({
      buildingId: row.id,
      buildingName: row.name,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseDormitoryBuildingSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);

  const [staffSelectorVisible, setStaffSelectorVisible] = useState(false);
  const findStaff = () => {
    setStaffSelectorVisible(true);
  }
  const handleStaffSelected = (selectedStaff: { staffId?: number; staffName?: string; }) => {
    setStaffSelectorVisible(false)
    if (selectedStaff && 'staffId' in selectedStaff) {
      dormitoryBuildingSelectorForm.setFieldsValue(Object.assign(dormitoryBuildingSelectorForm.getFieldsValue(), {
      staffId: selectedStaff['staffId'],
      staffName: selectedStaff['staffName'],
      }));
    }
  };
  const handleCloseStaffSelector = () => {
    setStaffSelectorVisible(false)
  };

  return (
    <Modal title={"宿舍楼栋信息选择器(双击行选中)"} open={visible} onCancel={onCloseDormitoryBuildingSelector}
        width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={dormitoryBuildingSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="楼栋名称">
          <Input maxLength={32} placeholder="请输入楼栋名称"/>
        </Form.Item>
        <Form.Item name="buildingType" label="楼栋类型">
          <Select placeholder="请选择楼栋类型" options={[
            { value: 1, label: <span>男生</span> },
            { value: 2, label: <span>女生</span> },
            { value: 3, label: <span>按楼层男女混住</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<DormitoryBuilding> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
      <StaffSelector visible={staffSelectorVisible} onStaffSelected={handleStaffSelected} onCloseStaffSelector={handleCloseStaffSelector} />
    </Modal>
  );
};

export default DormitoryBuildingSelector;

// v3_el/src/views/dormitoryBuilding/DormitoryBuildingSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="dormitoryBuildingQueryForm" ref="dormitoryBuildingQueryFormRef" :rules="rules">
        <el-form-item label="楼栋名称" prop="name">
          <el-input v-model="dormitoryBuildingQueryForm.name" placeholder="请输入楼栋名称" maxlength="32"></el-input>
        </el-form-item>
        <el-form-item label="楼栋类型" prop="buildingType">
          <el-select v-model="dormitoryBuildingQueryForm.buildingType" placeholder="请选择楼栋类型" class="select-custom">
            <el-option label="男生" :value="1"></el-option>
            <el-option label="女生" :value="2"></el-option>
            <el-option label="按楼层男女混住" :value="3"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="state.tableData"
        border
        v-loading="state.loading"
        size="small"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="dormitoryBuildingSelected">
        <el-table-column prop="name" label="楼栋名称"></el-table-column>
        <el-table-column prop="constructionYear" label="建筑年份"></el-table-column>
        <el-table-column prop="floorNumber" label="楼层"></el-table-column>
        <el-table-column prop="buildingType" label="楼栋类型">
          <template v-slot="{ row }">
            <div v-if="row.buildingType === 1">男生</div>
            <div v-if="row.buildingType === 2">女生</div>
            <div v-if="row.buildingType === 3">按楼层男女混住</div>
          </template>
        </el-table-column>
        <el-table-column prop="staffName" label="宿管姓名"></el-table-column>
        <el-table-column prop="buildingLocation" label="位置"></el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="changePage"
          :current-page="state.currentPage"
          :page-sizes="state.pageSizes"
          :page-size="state.pageSize"
          background
          layout="total, prev, pager, next, jumper"
          :total="state.total">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref, inject, toRefs, defineEmits} from 'vue';
import dormitoryBuildingApi from '@/api/dormitoryBuildingApi'
import type {DormitoryBuildingQueryForm} from "@/types/req/dormitoryBuildingQueryForm";
import type {DormitoryBuilding} from "@/types/resp/dormitoryBuilding";
import {ElMessage, ElMessageBox, type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";

const dormitoryBuildingQueryFormRef = ref<FormInstance | null>(null);
let dormitoryBuildingQueryForm = reactive<DormitoryBuildingQueryForm>({
  name: '',
  buildingType: undefined,
})
const staffSelectorVisible = ref<boolean>(false)

const state = reactive({
  loading: false,
  tableData: [] as DormitoryBuilding[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})

const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

const emit = defineEmits<{
  (e: 'dormitoryBuildingSelectedEvent', data?: {
    buildingId: number,
    buildingName: string,
    }): void;
}>()

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<DormitoryBuilding>> = await dormitoryBuildingApi.find(dormitoryBuildingQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
        const page: Page<DormitoryBuilding> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (dormitoryBuildingQueryFormRef.value) {
    dormitoryBuildingQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const dormitoryBuildingSelected = (row: DormitoryBuilding) => {
  emit('dormitoryBuildingSelectedEvent', {
    buildingId: row.id,
    buildingName: row.name,
  })
}


const onBack = () => {
  emit('dormitoryBuildingSelectedEvent')
}
</script>

<style lang="scss">
</style>
