// v2_el/src/views/staff/StaffAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="staffForm" :label-width="formLabelWidth" ref="refStaffForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="staffForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="phone">
            <el-input v-model="staffForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="岗位" prop="position">
            <el-input v-model="staffForm.position" placeholder="请输入岗位" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="特长" prop="specialty">
            <el-input v-model="staffForm.specialty" placeholder="请输入特长" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import staffApi from '@/api/staffApi'
export default {
  name: 'StaffAdd',
  components: {},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      staffForm: {
        name: '',
        phone: '',
        position: '',
        specialty: ''
      },
      rules: {
        name: [
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
        phone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        position: [
          { required: true, message: '请输入岗位', trigger: 'blur' }
        ],
      },
    }
  },
  created () {
    if (this.id) {
      staffApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.staffForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.staffForm = {
        name: '',
        phone: '',
        position: '',
        specialty: ''
      }
      this.$emit('reset-staff-add-event')
    },
    onSave () {
      this.$refs.refStaffForm.validate((valid) => {
        if (valid) {
          staffApi.save(this.staffForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-staff-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    onBack () {
      this.$emit('close-staff-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/staff/staff-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StaffService} from '../../service/staff.service';
import {SharedModule} from '../shared.module';
import {StaffForm} from '../../types/req/StaffForm';
import {MODAL_WIDTH} from '../../const'

@Component({
  selector: 'staff-add',
  imports: [
    SharedModule
  ],
  templateUrl: './staff-add.component.html',
  standalone: true
})
export class StaffAddComponent implements OnInit {
  staffToSave:StaffForm = {};
  staffForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增员工信息'
  modalWidth: string = MODAL_WIDTH
  


  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private staffService: StaffService
  ) {}

  ngOnInit(): void {
    this.staffForm = this.fb.group({
      name: ['', [Validators.required]],
      phone: ['', [Validators.required]],
      position: ['', [Validators.required]],
      specialty: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.staffForm.controls) {
        this.staffForm.controls[i].markAsDirty();
        this.staffForm.controls[i].updateValueAndValidity();
      }
      if (!this.staffForm.valid) {
        this.saveLoading = false
        return
      }
      this.staffService.save(Object.assign(this.staffToSave, this.staffForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增员工信息'.slice()
    this.staffForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改员工信息'
      this.saveLoading = true
      this.staffService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.staffToSave = resp.data
            this.staffForm.patchValue(this.staffToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="staffForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="phone" placeholder="请输入联系电话" maxlength="20"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="position" nzRequired>岗位</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入岗位'">
              <input nz-input formControlName="position" placeholder="请输入岗位" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="specialty">特长</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="specialty" placeholder="请输入特长" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
