// angular_ngzorro/src/app/dormitory-visitor/dormitory-visitor-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {DormitoryVisitorService} from '../../service/dormitory-visitor.service';
import {SharedModule} from '../shared.module';
import {DormitoryVisitorForm} from '../../types/req/DormitoryVisitorForm';
import {MODAL_WIDTH, DATE_FORMAT} from '../../const'
import {DormitoryRoomSelectorComponent} from '../dormitory-room/dormitory-room-selector.component';
import {StudentSelectorComponent} from '../student/student-selector.component';

@Component({
  selector: 'dormitory-visitor-add',
  imports: [
    DormitoryRoomSelectorComponent,
    StudentSelectorComponent,
    SharedModule
  ],
  templateUrl: './dormitory-visitor-add.component.html',
  standalone: true
})
export class DormitoryVisitorAddComponent implements OnInit {
  dormitoryVisitorToSave:DormitoryVisitorForm = {};
  dormitoryVisitorForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增访客记录'
  modalWidth: string = MODAL_WIDTH
  dateFormat: string = DATE_FORMAT

  @ViewChild(DormitoryRoomSelectorComponent, { static: false }) dormitoryRoomSelectorComponent!: DormitoryRoomSelectorComponent;
  @ViewChild(StudentSelectorComponent, { static: false }) studentSelectorComponent!: StudentSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private dormitoryVisitorService: DormitoryVisitorService
  ) {}

  ngOnInit(): void {
    this.dormitoryVisitorForm = this.fb.group({
      roomId: [0],
      roomNumber: ['', [Validators.required]],
      studentId: [0],
      studentName: ['', [Validators.required]],
      visitorName: ['', [Validators.required]],
      contactPhone: ['', [Validators.required]],
      visitStartTime: ['', [Validators.required]],
      visitEndTime: ['', [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.dormitoryVisitorForm.controls) {
        this.dormitoryVisitorForm.controls[i].markAsDirty();
        this.dormitoryVisitorForm.controls[i].updateValueAndValidity();
      }
      if (!this.dormitoryVisitorForm.valid) {
        this.saveLoading = false
        return
      }
      this.dormitoryVisitorService.save(Object.assign(this.dormitoryVisitorToSave, this.dormitoryVisitorForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增访客记录'.slice()
    this.dormitoryVisitorForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改访客记录'
      this.saveLoading = true
      this.dormitoryVisitorService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.dormitoryVisitorToSave = resp.data
            this.dormitoryVisitorForm.patchValue(this.dormitoryVisitorToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findDormitoryRoom() {
    this.dormitoryRoomSelectorComponent.display()
  }

  handleDormitoryRoomSelectedEvent(selectedDormitoryRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom) {
      this.dormitoryVisitorForm.patchValue(selectedDormitoryRoom);
    }
  }
  findStudent() {
    this.studentSelectorComponent.display()
  }

  handleStudentSelectedEvent(selectedStudent: { studentId?: number; studentName?: string; }) {
    if (selectedStudent && 'studentId' in selectedStudent) {
      this.dormitoryVisitorForm.patchValue(selectedStudent);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="dormitoryVisitorForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房间号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房间号'">
              <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
                <input nz-input formControlName="roomNumber" placeholder="请选择房间号" readonly />
              </nz-input-group>
              <ng-template #roomNumberSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findDormitoryRoom()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentName" nzRequired>学生姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择学生姓名'">
              <nz-input-group nzSearch [nzAddOnAfter]="studentNameSuffixIconButton">
                <input nz-input formControlName="studentName" placeholder="请选择学生姓名" readonly />
              </nz-input-group>
              <ng-template #studentNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findStudent()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="visitorName" nzRequired>访客姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入访客姓名'">
              <input nz-input formControlName="visitorName" placeholder="请输入访客姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>访客联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入访客联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入访客联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="visitStartTime">开始时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="visitStartTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="visitEndTime">结束时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="visitEndTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<dormitory-room-selector (dormitoryRoomSelectedEvent)="handleDormitoryRoomSelectedEvent($event)"></dormitory-room-selector>
<student-selector (studentSelectedEvent)="handleStudentSelectedEvent($event)"></student-selector>

// v2_el/src/views/dormitoryVisitor/DormitoryVisitorAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="dormitoryVisitorForm" :label-width="formLabelWidth" ref="refDormitoryVisitorForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房间号" prop="roomNumber">
            <el-input v-model="dormitoryVisitorForm.roomNumber" placeholder="请选择房间号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findDormitoryRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="学生姓名" prop="studentName">
            <el-input v-model="dormitoryVisitorForm.studentName" placeholder="请选择学生姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStudent"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="访客姓名" prop="visitorName">
            <el-input v-model="dormitoryVisitorForm.visitorName" placeholder="请输入访客姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="访客联系电话" prop="contactPhone">
            <el-input v-model="dormitoryVisitorForm.contactPhone" placeholder="请输入访客联系电话" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="开始时间" prop="visitStartTime">
            <el-date-picker
                v-model="dormitoryVisitorForm.visitStartTime" type="datetime" placeholder="开始时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="结束时间" prop="visitEndTime">
            <el-date-picker
                v-model="dormitoryVisitorForm.visitEndTime" type="datetime" placeholder="结束时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="dormitoryRoomSelectorVisible" v-if="dormitoryRoomSelectorVisible" title="宿舍房间信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <dormitory-room-selector @dormitory-room-selected-event="handleDormitoryRoomSelectedEvent">
      </dormitory-room-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentSelectorVisible" v-if="studentSelectorVisible" title="学生信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <student-selector @student-selected-event="handleStudentSelectedEvent">
      </student-selector>
    </el-dialog>
  </div>
</template>

<script>
import dormitoryVisitorApi from '@/api/dormitoryVisitorApi'
import DormitoryRoomSelector from "@/views/dormitoryRoom/DormitoryRoomSelector.vue";
import StudentSelector from "@/views/student/StudentSelector.vue";
export default {
  name: 'DormitoryVisitorAdd',
  components: {DormitoryRoomSelector,StudentSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      dormitoryVisitorForm: {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
        visitorName: '',
        contactPhone: '',
        visitStartTime: '',
        visitEndTime: ''
      },
      rules: {
        roomNumber: [
          { required: true, message: '请输入房间号', trigger: 'blur' }
        ],
        studentName: [
          { required: true, message: '请输入学生姓名', trigger: 'blur' }
        ],
        visitorName: [
          { required: true, message: '请输入访客姓名', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入访客联系电话', trigger: 'blur' }
        ],
        visitStartTime: [
          { required: true, message: '请输入开始时间', trigger: 'blur' }
        ],
        visitEndTime: [
          { required: true, message: '请输入结束时间', trigger: 'blur' }
        ],
      },
      dormitoryRoomSelectorVisible: false,
      studentSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      dormitoryVisitorApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.dormitoryVisitorForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.dormitoryVisitorForm = {
        roomId: '',
        roomNumber: '',
        studentId: '',
        studentName: '',
        visitorName: '',
        contactPhone: '',
        visitStartTime: '',
        visitEndTime: ''
      }
      this.$emit('reset-dormitory-visitor-add-event')
    },
    onSave () {
      this.$refs.refDormitoryVisitorForm.validate((valid) => {
        if (valid) {
          dormitoryVisitorApi.save(this.dormitoryVisitorForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-dormitory-visitor-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findDormitoryRoom () {
      this.dormitoryRoomSelectorVisible = true
    },
    handleDormitoryRoomSelectedEvent (selectedDormitoryRoom) {
      this.dormitoryRoomSelectorVisible = false
      if (selectedDormitoryRoom && 'roomId' in selectedDormitoryRoom && this.dormitoryVisitorForm.roomId !== selectedDormitoryRoom['roomId']) {
        this.dormitoryVisitorForm.roomId = selectedDormitoryRoom['roomId']
        this.dormitoryVisitorForm.roomNumber = selectedDormitoryRoom['roomNumber']
      }
    },
    findStudent () {
      this.studentSelectorVisible = true
    },
    handleStudentSelectedEvent (selectedStudent) {
      this.studentSelectorVisible = false
      if (selectedStudent && 'studentId' in selectedStudent && this.dormitoryVisitorForm.studentId !== selectedStudent['studentId']) {
        this.dormitoryVisitorForm.studentId = selectedStudent['studentId']
        this.dormitoryVisitorForm.studentName = selectedStudent['studentName']
      }
    },
    onBack () {
      this.$emit('close-dormitory-visitor-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
